/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface RetrieveNumberListResponseItem {
    /**
     * Number provider:
     * - `byo`: BYO (Bring Your Own).
     * - `twilio`: Twilio.
     */
    provider?: RetrieveNumberListResponseItem.Provider;
    /** A telephone number in E.164 format, used as a unique identifier. */
    phone_number?: string;
    /** A label used to identify the number. */
    label?: string;
    /** Whether the number supports inbound calls. */
    inbound?: boolean;
    /** Whether the number supports outbound calls. */
    outbound?: boolean;
    /** The associated pipeline information. Returns `null` if no pipeline is associated. */
    associated_pipeline?: RetrieveNumberListResponseItem.AssociatedPipeline;
    /** SIP inbound call configuration details. Returns `null` if not configured. */
    inbound_config?: Record<string, unknown>;
    /** SIP outbound call configuration details. Returns `null` if not configured. */
    outbound_config?: Record<string, unknown>;
}

export namespace RetrieveNumberListResponseItem {
    /**
     * Number provider:
     * - `byo`: BYO (Bring Your Own).
     * - `twilio`: Twilio.
     */
    export type Provider = "byo" | "twilio";
    export const Provider = {
        Byo: "byo",
        Twilio: "twilio",
    } as const;

    /**
     * The associated pipeline information. Returns `null` if no pipeline is associated.
     */
    export interface AssociatedPipeline {
        /** Pipeline ID. */
        pipeline_id?: string;
        /** Pipeline name. */
        pipeline_name?: string;
    }
}
