/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Agora from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace PhoneNumberManagement {
    export interface Options {
        environment?: core.Supplier<environments.AgoraEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        username: core.Supplier<string>;
        password: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

/**
 * Operations for managing phone numbers
 */
export class PhoneNumberManagement {
    protected readonly _options: PhoneNumberManagement.Options;

    constructor(_options: PhoneNumberManagement.Options) {
        this._options = _options;
    }

    /**
     * Retrieve a list of all imported phone numbers under the current account.
     *
     * @param {PhoneNumberManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.phoneNumberManagement.retrieveNumberList()
     */
    public retrieveNumberList(
        requestOptions?: PhoneNumberManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.RetrieveNumberListResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(this.__retrieveNumberList(requestOptions));
    }

    private async __retrieveNumberList(
        requestOptions?: PhoneNumberManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.RetrieveNumberListResponseItem[]>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                "v2/phone-numbers",
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Agora.RetrieveNumberListResponseItem[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError("Timeout exceeded when calling GET /v2/phone-numbers.");
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Import a pre-configured phone number that can be used for inbound or outbound calls.
     *
     * @param {Agora.ImportNumberRequest} request
     * @param {PhoneNumberManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.phoneNumberManagement.importNumber({
     *         provider: "byo",
     *         phone_number: "+19876543210",
     *         label: "Sales Hotline",
     *         inbound: true,
     *         outbound: true,
     *         inbound_config: {
     *             allowed_addresses: ["112.126.15.64/27"]
     *         },
     *         outbound_config: {
     *             address: "xxx:xxx@sip.example.com",
     *             transport: "tls"
     *         }
     *     })
     */
    public importNumber(
        request: Agora.ImportNumberRequest,
        requestOptions?: PhoneNumberManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.ImportNumberResponse> {
        return core.HttpResponsePromise.fromPromise(this.__importNumber(request, requestOptions));
    }

    private async __importNumber(
        request: Agora.ImportNumberRequest,
        requestOptions?: PhoneNumberManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.ImportNumberResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                "v2/phone-numbers",
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.ImportNumberResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError("Timeout exceeded when calling POST /v2/phone-numbers.");
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve detailed information for a specific phone number.
     *
     * @param {string} phoneNumber - Telephone number in E.164 format. For example, +11234567890.
     * @param {PhoneNumberManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.phoneNumberManagement.retrieveNumberInformation("phone_number")
     */
    public retrieveNumberInformation(
        phoneNumber: string,
        requestOptions?: PhoneNumberManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.RetrieveNumberInformationResponse> {
        return core.HttpResponsePromise.fromPromise(this.__retrieveNumberInformation(phoneNumber, requestOptions));
    }

    private async __retrieveNumberInformation(
        phoneNumber: string,
        requestOptions?: PhoneNumberManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.RetrieveNumberInformationResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/phone-numbers/${encodeURIComponent(phoneNumber)}`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Agora.RetrieveNumberInformationResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling GET /v2/phone-numbers/{phone_number}.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Remove an imported phone number from the system.
     *
     * Note: This operation only removes the number configuration from the Agora system; the number stored with the phone service provider is not deleted. After calling this endpoint, the number stops receiving calls routed through this system. To delete the number from the service provider, remove it in the service provider's console.
     *
     * @param {string} phoneNumber - Telephone number in E.164 format. For example, +11234567890.
     * @param {PhoneNumberManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.phoneNumberManagement.deleteNumber("phone_number")
     */
    public deleteNumber(
        phoneNumber: string,
        requestOptions?: PhoneNumberManagement.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__deleteNumber(phoneNumber, requestOptions));
    }

    private async __deleteNumber(
        phoneNumber: string,
        requestOptions?: PhoneNumberManagement.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/phone-numbers/${encodeURIComponent(phoneNumber)}`,
            ),
            method: "DELETE",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling DELETE /v2/phone-numbers/{phone_number}.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Update the configuration for a phone number.
     *
     * @param {string} phoneNumber - Telephone number in E.164 format. For example, +11234567890.
     * @param {Agora.UpdateNumberConfigurationRequest} request
     * @param {PhoneNumberManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.phoneNumberManagement.updateNumberConfiguration("phone_number", {
     *         inbound_config: {
     *             pipeline_id: "xxxxx"
     *         },
     *         outbound_config: {
     *             pipeline_id: "xxxxx"
     *         }
     *     })
     */
    public updateNumberConfiguration(
        phoneNumber: string,
        request: Agora.UpdateNumberConfigurationRequest = {},
        requestOptions?: PhoneNumberManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.UpdateNumberConfigurationResponse> {
        return core.HttpResponsePromise.fromPromise(
            this.__updateNumberConfiguration(phoneNumber, request, requestOptions),
        );
    }

    private async __updateNumberConfiguration(
        phoneNumber: string,
        request: Agora.UpdateNumberConfigurationRequest = {},
        requestOptions?: PhoneNumberManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.UpdateNumberConfigurationResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/phone-numbers/${encodeURIComponent(phoneNumber)}`,
            ),
            method: "PATCH",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Agora.UpdateNumberConfigurationResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling PATCH /v2/phone-numbers/{phone_number}.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        return core.BasicAuth.toAuthorizationHeader({
            username: await core.Supplier.get(this._options.username),
            password: await core.Supplier.get(this._options.password),
        });
    }
}
