// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "../../../../BaseClient.js";
import { normalizeClientOptions } from "../../../../BaseClient.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as core from "../../../../core/index.js";
import * as environments from "../../../../environments.js";
import * as errors from "../../../../errors/index.js";
import type * as Agora from "../../../index.js";

export declare namespace PhoneNumberManagementClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * Operations for managing phone numbers
 */
export class PhoneNumberManagementClient {
    protected readonly _options: PhoneNumberManagementClient.Options;

    constructor(options: PhoneNumberManagementClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    /**
     * Retrieve a list of all imported phone numbers under the current account.
     *
     * @param {PhoneNumberManagementClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.phoneNumberManagement.list()
     */
    public list(
        requestOptions?: PhoneNumberManagementClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.ListPhoneNumberManagementResponseItem[]> {
        return core.HttpResponsePromise.fromPromise(this.__list(requestOptions));
    }

    private async __list(
        requestOptions?: PhoneNumberManagementClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.ListPhoneNumberManagementResponseItem[]>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                "v2/phone-numbers",
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Agora.ListPhoneNumberManagementResponseItem[],
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError("Timeout exceeded when calling GET /v2/phone-numbers.");
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Import a pre-configured phone number that can be used for inbound or outbound calls.
     *
     * @param {Agora.AddPhoneNumberManagementRequest} request
     * @param {PhoneNumberManagementClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.phoneNumberManagement.add({
     *         provider: "byo",
     *         phone_number: "+19876543210",
     *         label: "Sales Hotline",
     *         inbound: true,
     *         outbound: true,
     *         inbound_config: {
     *             allowed_addresses: ["112.126.15.64/27"]
     *         },
     *         outbound_config: {
     *             address: "xxx:xxx@sip.example.com",
     *             transport: "tls"
     *         }
     *     })
     */
    public add(
        request: Agora.AddPhoneNumberManagementRequest,
        requestOptions?: PhoneNumberManagementClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.AddPhoneNumberManagementResponse> {
        return core.HttpResponsePromise.fromPromise(this.__add(request, requestOptions));
    }

    private async __add(
        request: Agora.AddPhoneNumberManagementRequest,
        requestOptions?: PhoneNumberManagementClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.AddPhoneNumberManagementResponse>> {
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                "v2/phone-numbers",
            ),
            method: "POST",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Agora.AddPhoneNumberManagementResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError("Timeout exceeded when calling POST /v2/phone-numbers.");
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve detailed information for a specific phone number.
     *
     * @param {Agora.GetPhoneNumberManagementRequest} request
     * @param {PhoneNumberManagementClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.phoneNumberManagement.get({
     *         phone_number: "phone_number"
     *     })
     */
    public get(
        request: Agora.GetPhoneNumberManagementRequest,
        requestOptions?: PhoneNumberManagementClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.GetPhoneNumberManagementResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(request, requestOptions));
    }

    private async __get(
        request: Agora.GetPhoneNumberManagementRequest,
        requestOptions?: PhoneNumberManagementClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.GetPhoneNumberManagementResponse>> {
        const { phone_number: phoneNumber } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/phone-numbers/${core.url.encodePathParam(phoneNumber)}`,
            ),
            method: "GET",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Agora.GetPhoneNumberManagementResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling GET /v2/phone-numbers/{phone_number}.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Remove an imported phone number from the system.
     *
     * Note: This operation only removes the number configuration from the Agora system; the number stored with the phone service provider is not deleted. After calling this endpoint, the number stops receiving calls routed through this system. To delete the number from the service provider, remove it in the service provider's console.
     *
     * @param {Agora.DeletePhoneNumberManagementRequest} request
     * @param {PhoneNumberManagementClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.phoneNumberManagement.delete({
     *         phone_number: "phone_number"
     *     })
     */
    public delete(
        request: Agora.DeletePhoneNumberManagementRequest,
        requestOptions?: PhoneNumberManagementClient.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__delete(request, requestOptions));
    }

    private async __delete(
        request: Agora.DeletePhoneNumberManagementRequest,
        requestOptions?: PhoneNumberManagementClient.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const { phone_number: phoneNumber } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/phone-numbers/${core.url.encodePathParam(phoneNumber)}`,
            ),
            method: "DELETE",
            headers: _headers,
            queryParameters: requestOptions?.queryParams,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling DELETE /v2/phone-numbers/{phone_number}.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Update the configuration for a phone number.
     *
     * @param {Agora.UpdatePhoneNumberManagementRequest} request
     * @param {PhoneNumberManagementClient.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.phoneNumberManagement.update({
     *         phone_number: "phone_number",
     *         inbound_config: {
     *             pipeline_id: "xxxxx"
     *         },
     *         outbound_config: {
     *             pipeline_id: "xxxxx"
     *         }
     *     })
     */
    public update(
        request: Agora.UpdatePhoneNumberManagementRequest,
        requestOptions?: PhoneNumberManagementClient.RequestOptions,
    ): core.HttpResponsePromise<Agora.UpdatePhoneNumberManagementResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(request, requestOptions));
    }

    private async __update(
        request: Agora.UpdatePhoneNumberManagementRequest,
        requestOptions?: PhoneNumberManagementClient.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.UpdatePhoneNumberManagementResponse>> {
        const { phone_number: phoneNumber, ..._body } = request;
        const _headers: core.Fetcher.Args["headers"] = mergeHeaders(
            this._options?.headers,
            mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
            requestOptions?.headers,
        );
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/phone-numbers/${core.url.encodePathParam(phoneNumber)}`,
            ),
            method: "PATCH",
            headers: _headers,
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: _body,
            timeoutMs: (requestOptions?.timeoutInSeconds ?? this._options?.timeoutInSeconds ?? 60) * 1000,
            maxRetries: requestOptions?.maxRetries ?? this._options?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
            fetchFn: this._options?.fetch,
            logging: this._options.logging,
        });
        if (_response.ok) {
            return {
                data: _response.body as Agora.UpdatePhoneNumberManagementResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling PATCH /v2/phone-numbers/{phone_number}.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        return core.BasicAuth.toAuthorizationHeader({
            username: await core.Supplier.get(this._options.username),
            password: await core.Supplier.get(this._options.password),
        });
    }
}
