// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         appid: "appid",
 *         agentId: "agentId"
 *     }
 */
export interface GetHistoryAgentsRequest {
    /** The App ID of the project. */
    appid: string;
    /** The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent. */
    agentId: string;
}
