// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         appid: "appid",
 *         name: "unique_name",
 *         properties: {
 *             channel: "channel_name",
 *             token: "token",
 *             agent_rtc_uid: "1001",
 *             remote_rtc_uids: ["1002"],
 *             idle_timeout: 120,
 *             advanced_features: {
 *                 enable_aivad: true
 *             },
 *             asr: {
 *                 language: "en-US"
 *             },
 *             tts: {
 *                 vendor: "microsoft",
 *                 params: {
 *                     "key": "<your_tts_api_key>",
 *                     "region": "eastus",
 *                     "voice_name": "en-US-AndrewMultilingualNeural"
 *                 }
 *             },
 *             llm: {
 *                 url: "https://api.openai.com/v1/chat/completions",
 *                 api_key: "<your_llm_key>",
 *                 system_messages: [{
 *                         "role": "system",
 *                         "content": "You are a helpful chatbot."
 *                     }],
 *                 params: {
 *                     "model": "gpt-4o-mini"
 *                 },
 *                 max_history: 32,
 *                 greeting_message: "Hello, how can I assist you today?",
 *                 failure_message: "Please hold on a second."
 *             }
 *         }
 *     }
 */
export interface StartAgentsRequest {
    /** The App ID of the project. */
    appid: string;
    /** The unique identifier of the agent. The same identifier cannot be used repeatedly. */
    name: string;
    /** Configuration details of the agent. */
    properties: StartAgentsRequest.Properties;
}

export namespace StartAgentsRequest {
    /**
     * Configuration details of the agent.
     */
    export interface Properties {
        /** The name of the channel to join. */
        channel: string;
        /** The authentication token used by the agent to join the channel. */
        token: string;
        /** The user ID of the agent in the channel. A value of `0` means that a random UID is generated and assigned. Set the `token` accordingly. */
        agent_rtc_uid: string;
        /** A list of user IDs that the agent subscribes to in the channel. Only subscribed users can interact with the agent. Currently, only one user ID is supported. */
        remote_rtc_uids: string[];
        /**
         * Whether to enable String uid:
         * - `true`: Both agent and subscriber user IDs use strings.
         * - `false`: Both agent and subscriber user IDs must be integers.
         */
        enable_string_uid?: boolean;
        /** Sets the timeout after all the users specified in `remote_rtc_uids` are detected to have left the channel. When the timeout value is exceeded, the agent automatically stops and exits the channel. A value of `0` means that the agent does not exit until it is stopped manually. */
        idle_timeout?: number;
        /** Advanced features configuration. */
        advanced_features?: Properties.AdvancedFeatures;
        /** Automatic Speech Recognition (ASR) configuration. */
        asr?: Properties.Asr;
        /** Text-to-speech (TTS) module configuration. */
        tts: Properties.Tts;
        /** Large language model (LLM) configuration. */
        llm: Properties.Llm;
        /** Multimodal Large Language Model (MLLM) configuration for real-time audio and text processing. */
        mllm?: Properties.Mllm;
        /** Avatar configuration. */
        avatar?: Properties.Avatar;
        /** Conversation turn detection settings. */
        turn_detection?: Properties.TurnDetection;
        /** Selective Attention Locking (SAL) configuration. */
        sal?: Properties.Sal;
        /** Agent configuration parameters. */
        parameters?: Properties.Parameters;
    }

    export namespace Properties {
        /**
         * Advanced features configuration.
         */
        export interface AdvancedFeatures {
            /** Whether to enable the intelligent interruption handling function (AIVAD). This feature is currently available only for English. */
            enable_aivad?: boolean;
            /** Enable Multimodal Large Language Model. Enabling MLLM automatically disables ASR, LLM, and TTS. When you set this parameter to true, `enable_aivad` is also disabled. */
            enable_mllm?: boolean;
            /** Whether to enable the Signaling (RTM) service. When enabled, the agent can combine the capabilities provided by Signaling to implement advanced functions, such as delivering custom information. Before enabling the Signaling service, make sure the token includes both RTC and RTM privileges. */
            enable_rtm?: boolean;
            /** Enable Selective Attention Locking (SAL). When enabled, configure the `sal` field to set up speaker recognition or locking modes. */
            enable_sal?: boolean;
        }

        /**
         * Automatic Speech Recognition (ASR) configuration.
         */
        export interface Asr {
            /** The BCP-47 language tag identifying the primary language used for agent interaction. If `params` contains a vendor-specific language code, it takes precedence over this setting. */
            language?: string;
            /**
             * ASR provider:
             * - `ares`: Adaptive Recognition Engine for Speech
             * - `microsoft`: Microsoft Azure
             * - `deepgram`: Deepgram
             * - `openai`: OpenAI (Beta)
             * - `speechmatics`: Speechmatics
             * - `assemblyai`: AssemblyAI (Beta)
             * - `amazon`: Amazon Transcribe (Beta)
             * - `google`: Google (Beta)
             */
            vendor?: Asr.Vendor;
            /** The configuration parameters for the ASR vendor. See [ASR Overview](https://docs.agora.io/en/conversational-ai/models/asr/overview) for details. */
            params?: Record<string, unknown>;
        }

        export namespace Asr {
            /**
             * ASR provider:
             * - `ares`: Adaptive Recognition Engine for Speech
             * - `microsoft`: Microsoft Azure
             * - `deepgram`: Deepgram
             * - `openai`: OpenAI (Beta)
             * - `speechmatics`: Speechmatics
             * - `assemblyai`: AssemblyAI (Beta)
             * - `amazon`: Amazon Transcribe (Beta)
             * - `google`: Google (Beta)
             */
            export const Vendor = {
                Ares: "ares",
                Microsoft: "microsoft",
                Deepgram: "deepgram",
                Openai: "openai",
                Google: "google",
                Amazon: "amazon",
                Assemblyai: "assemblyai",
                Speechmatics: "speechmatics",
            } as const;
            export type Vendor = (typeof Vendor)[keyof typeof Vendor];
        }

        /**
         * Text-to-speech (TTS) module configuration.
         */
        export interface Tts {
            /**
             * TTS provider:
             * - `microsoft`: Microsoft Azure
             * - `elevenlabs`: ElevenLabs
             * - `cartesia`: Cartesia (Beta)
             * - `openai`: OpenAI (Beta)
             * - `humeai`: Hume AI (Beta)
             * - `rime`: Rime (Beta)
             * - `fishaudio`: Fish Audio (Beta)
             * - `groq`: Groq (Beta)
             * - `google`: Google (Beta)
             * - `amazon`: Amazon Polly (Beta)
             */
            vendor: Tts.Vendor;
            /** The configuration parameters for the TTS vendor. See [TTS Overview](https://docs.agora.io/en/conversational-ai/models/tts/overview) for details. */
            params: Record<string, unknown>;
            /**
             * Controls whether the TTS module skips bracketed content when reading LLM response text. Enable this feature by specifying one or more values:
             * - `1`: Skip content in Chinese parentheses （）
             * - `2`: Skip content in Chinese square brackets 【】
             * - `3`: Skip content in parentheses ( )
             * - `4`: Skip content in square brackets [ ]
             * - `5`: Skip content in curly braces { }
             *
             * > - **Nested brackets**: When input text contains nested brackets and multiple bracket types are configured to be skipped, the system processes only the outermost brackets. The system matches from the beginning of the text and skips the first outermost bracket pair that meets the skip rule, including all nested content.
             * > - **Agent memory**: The agent's short-term memory always contains the complete, unfiltered LLM text, regardless of live captioning settings.
             * > - **Real-time transcript**: When enabled, transcript excludes filtered content during TTS playback but restores the complete text after each sentence finishes.
             */
            skip_patterns?: number[];
        }

        export namespace Tts {
            /**
             * TTS provider:
             * - `microsoft`: Microsoft Azure
             * - `elevenlabs`: ElevenLabs
             * - `cartesia`: Cartesia (Beta)
             * - `openai`: OpenAI (Beta)
             * - `humeai`: Hume AI (Beta)
             * - `rime`: Rime (Beta)
             * - `fishaudio`: Fish Audio (Beta)
             * - `groq`: Groq (Beta)
             * - `google`: Google (Beta)
             * - `amazon`: Amazon Polly (Beta)
             */
            export const Vendor = {
                Microsoft: "microsoft",
                Elevenlabs: "elevenlabs",
                Cartesia: "cartesia",
                Openai: "openai",
                Humeai: "humeai",
                Rime: "rime",
                Fishaudio: "fishaudio",
                Groq: "groq",
                Google: "google",
                Amazon: "amazon",
            } as const;
            export type Vendor = (typeof Vendor)[keyof typeof Vendor];
        }

        /**
         * Large language model (LLM) configuration.
         */
        export interface Llm {
            /** The LLM callback address. */
            url: string;
            /** The LLM verification API key. The default value is an empty string. Ensure that you enable the API key in a production environment. */
            api_key?: string;
            /** A set of predefined information used as input to the LLM, including prompt words and examples. */
            system_messages?: Record<string, unknown>[];
            /** Additional LLM configuration parameters, such as the `model` used, and the maximum token limit. For details about each supported LLM, refer to [Supported LLMs](https://docs.agora.io/en/conversational-ai/models/llm/overview#supported-llms). */
            params?: Record<string, unknown>;
            /** The number of conversation history messages cached in the custom LLM. History includes user and agent dialog messages, tool call information, and timestamps. Agent and user messages are recorded separately. */
            max_history?: number;
            /**
             * LLM input modalities:
             * - `["text"]`: Text only
             * - `["text", "image"]`: Text plus image; requires the selected LLM to support visual input
             */
            input_modalities?: string[];
            /**
             * LLM output modalities:
             * - `["text"]`: The output text is converted to speech by the TTS module and then published to the RTC channel.
             * - `["audio"]`: Voice only. Voice is published directly to the RTC channel.
             * - `["text", "audio"]`: Text plus voice. Write your own logic to process the output of LLM as needed.
             */
            output_modalities?: string[];
            /** Agent greeting. If provided, the first user in the channel is automatically greeted with the message upon joining. */
            greeting_message?: string;
            /** Prompt for agent activation failure. If provided, it is returned through TTS when the custom LLM call fails. */
            failure_message?: string;
            /**
             * LLM provider, supports the following settings:
             * - `custom`: Custom LLM. When you set this option, the agent includes the following fields, in addition to `role` and `content` when making requests to the custom LLM:
             *   - `turn_id`: A unique identifier for each conversation turn. It starts from `0` and increments with each turn. One user-agent interaction corresponds to one `turn_id`.
             *   - `timestamp`: The request timestamp, in milliseconds.
             * - `azure`: Use this value for Azure OpenAI
             */
            vendor?: string;
            /**
             * The request style for chat completion:
             * - `openai`: For OpenAI and OpenAI-compatible APIs
             * - `gemini`: For Google Gemini and Google Vertex API format
             * - `anthropic`: For Anthropic Claude API format
             * - `dify`: For Dify API format
             */
            style?: Llm.Style;
        }

        export namespace Llm {
            /**
             * The request style for chat completion:
             * - `openai`: For OpenAI and OpenAI-compatible APIs
             * - `gemini`: For Google Gemini and Google Vertex API format
             * - `anthropic`: For Anthropic Claude API format
             * - `dify`: For Dify API format
             */
            export const Style = {
                Openai: "openai",
                Gemini: "gemini",
                Anthropic: "anthropic",
                Dify: "dify",
            } as const;
            export type Style = (typeof Style)[keyof typeof Style];
        }

        /**
         * Multimodal Large Language Model (MLLM) configuration for real-time audio and text processing.
         */
        export interface Mllm {
            /** The MLLM WebSocket URL for real-time communication. */
            url?: string;
            /** The API key used for MLLM authentication. */
            api_key?: string;
            /** Array of conversation items used for short-term memory management. Uses the same structure as `item.content` from the OpenAI Realtime API. */
            messages?: Record<string, unknown>[];
            /** Additional MLLM configuration parameters. The `modalities` setting is overridden by `input_modalities` and `output_modalities`. The `turn_detection` setting is overridden by the `turn_detection` section outside of `mllm`. */
            params?: Record<string, unknown>;
            /**
             * MLLM input modalities:
             * - `["audio"]`: Audio only
             * - `["audio", "text"]`: Audio plus text
             */
            input_modalities?: string[];
            /**
             * MLLM output modalities:
             * - `["text", "audio"]`: Text plus audio
             */
            output_modalities?: string[];
            /** Agent greeting message. If provided, the first user in the channel is automatically greeted with this message upon joining. */
            greeting_message?: string;
            /**
             * MLLM provider. Currently supports:
             * - `openai`: OpenAI Realtime API
             * - `vertexai`: Use this for Google Gemini Live
             */
            vendor?: Mllm.Vendor;
            /**
             * The request style for MLLM completion:
             * - `openai`: For OpenAI Realtime API format
             */
            style?: "openai";
        }

        export namespace Mllm {
            /**
             * MLLM provider. Currently supports:
             * - `openai`: OpenAI Realtime API
             * - `vertexai`: Use this for Google Gemini Live
             */
            export const Vendor = {
                Openai: "openai",
                Vertexai: "vertexai",
            } as const;
            export type Vendor = (typeof Vendor)[keyof typeof Vendor];
        }

        /**
         * Avatar configuration.
         */
        export interface Avatar {
            /** Whether to enable the avatar function for the agent. To enable, set to `true` and configure the `vendor` and `params` fields. */
            enable?: boolean;
            /**
             * Avatar vendor. Supports the following values:
             * - `akool`: Akool (Beta)
             * - `heygen`: HeyGen (Beta)
             */
            vendor?: Avatar.Vendor;
            /** The configuration parameters for the avatar vendor. See [AI Avatar Overview](https://docs.agora.io/en/conversational-ai/models/avatar/overview) for details. */
            params?: Record<string, unknown>;
        }

        export namespace Avatar {
            /**
             * Avatar vendor. Supports the following values:
             * - `akool`: Akool (Beta)
             * - `heygen`: HeyGen (Beta)
             */
            export const Vendor = {
                Akool: "akool",
                Heygen: "heygen",
            } as const;
            export type Vendor = (typeof Vendor)[keyof typeof Vendor];
        }

        /**
         * Conversation turn detection settings.
         */
        export interface TurnDetection {
            /**
             * Turn detection mechanism:
             * - `agora_vad`: Agora VAD
             * - `server_vad`: The model detects the start and end of speech based on audio volume. Only available when `mllm` is enabled and OpenAI is selected.
             * - `semantic_vad`: Uses a turn detection model with VAD to semantically estimate whether the user has finished speaking. Only available when `mllm` is enabled and OpenAI is selected.
             */
            type?: TurnDetection.Type;
            /**
             * Sets the agent's behavior when human voice interrupts the agent while it is interacting (speaking or thinking):
             * - `interrupt`: The agent immediately stops the current interaction and processes the human voice input.
             * - `append`: The agent completes the current interaction, then processes the human voice input.
             * - `ignore`: The agent discards the human voice input without processing or storing it in the context.
             * - `keyword`: The agent stops its current interaction after detecting any of the keywords specified in `interrupt_keywords`.
             * - `adaptive`: The agent dynamically increases the voice continuity threshold while speaking to reduce accidental interruptions.
             */
            interrupt_mode?: TurnDetection.InterruptMode;
            /** The amount of time in milliseconds that the user's voice must exceed the VAD threshold before an interruption is triggered. */
            interrupt_duration_ms?: number;
            /** Specifies the list of keywords that trigger an interruption when `interrupt_mode` is set to `keyword`. You can configure up to 128 keywords. */
            interrupt_keywords?: string[];
            /** The extra forward padding time in milliseconds before the processing system starts to process the speech input. This padding helps capture the beginning of the speech. */
            prefix_padding_ms?: number;
            /** The duration of audio silence in milliseconds. If no voice activity is detected during this period, the agent assumes that the user has stopped speaking. */
            silence_duration_ms?: number;
            /** Identification sensitivity determines the level of sound in the audio signal that is considered voice activity. Lower values make it easier for the agent to detect speech, and higher values ignore weak sounds. */
            threshold?: number;
            /** Whether to automatically generate a response when a VAD stop event occurs. Only available in `server_vad` and `semantic_vad` modes when using OpenAI Realtime API. */
            create_response?: boolean;
            /** Whether to automatically interrupt any ongoing response when a VAD start event occurs. Only available in `server_vad` and `semantic_vad` modes when using OpenAI Realtime API. */
            interrupt_response?: boolean;
            /**
             * The eagerness of the model to respond:
             * - `auto`: Equivalent to medium
             * - `low`: Wait longer for the user to continue speaking
             * - `high`: Respond more quickly
             *
             * Only available in `semantic_vad` mode when using OpenAI Realtime API.
             */
            eagerness?: TurnDetection.Eagerness;
        }

        export namespace TurnDetection {
            /**
             * Turn detection mechanism:
             * - `agora_vad`: Agora VAD
             * - `server_vad`: The model detects the start and end of speech based on audio volume. Only available when `mllm` is enabled and OpenAI is selected.
             * - `semantic_vad`: Uses a turn detection model with VAD to semantically estimate whether the user has finished speaking. Only available when `mllm` is enabled and OpenAI is selected.
             */
            export const Type = {
                AgoraVad: "agora_vad",
                ServerVad: "server_vad",
                SemanticVad: "semantic_vad",
            } as const;
            export type Type = (typeof Type)[keyof typeof Type];
            /**
             * Sets the agent's behavior when human voice interrupts the agent while it is interacting (speaking or thinking):
             * - `interrupt`: The agent immediately stops the current interaction and processes the human voice input.
             * - `append`: The agent completes the current interaction, then processes the human voice input.
             * - `ignore`: The agent discards the human voice input without processing or storing it in the context.
             * - `keyword`: The agent stops its current interaction after detecting any of the keywords specified in `interrupt_keywords`.
             * - `adaptive`: The agent dynamically increases the voice continuity threshold while speaking to reduce accidental interruptions.
             */
            export const InterruptMode = {
                Interrupt: "interrupt",
                Append: "append",
                Ignore: "ignore",
                Keyword: "keyword",
                Adaptive: "adaptive",
            } as const;
            export type InterruptMode = (typeof InterruptMode)[keyof typeof InterruptMode];
            /**
             * The eagerness of the model to respond:
             * - `auto`: Equivalent to medium
             * - `low`: Wait longer for the user to continue speaking
             * - `high`: Respond more quickly
             *
             * Only available in `semantic_vad` mode when using OpenAI Realtime API.
             */
            export const Eagerness = {
                Auto: "auto",
                Low: "low",
                High: "high",
            } as const;
            export type Eagerness = (typeof Eagerness)[keyof typeof Eagerness];
        }

        /**
         * Selective Attention Locking (SAL) configuration.
         */
        export interface Sal {
            /**
             * Selective attention lock mode:
             * - `locking`: Speaker Lock Mode. The agent locks onto the speaker, blocking 95% of ambient human voices and noise. You can enable this mode in two ways:
             *   - Seamless mode: When a user speaks loudly and clearly at the beginning of a conversation, the intelligent agent automatically recognizes the user as the speaker.
             *   - Personalized mode: When creating an agent, a speaker's voiceprint URL is pre-registered through the `sample_urls` field. The agent then locates the speaker based on the pre-registered voiceprint.
             * - `recognition`: Voiceprint recognition mode. The agent identifies different speakers and suppresses other background voices and environmental noise.
             */
            sal_mode?: Sal.SalMode;
            /**
             * The registered voiceprint URLs as key-value pairs, where each key is the voiceprint name and each value is the download URL for that speaker's voiceprint.
             * > - Do not set the incoming voiceprint name to "unknown"; this is a reserved keyword used to identify unknown speakers.
             * > - For a registered voiceprint, ensure that:
             * >   - Quantity: You must register at least 1 voiceprint URL, with a maximum of 3 per task request.
             * >   - Size: A single voiceprint file must not exceed 2 MB.
             * >   - Duration: 10 to 15 seconds, with at least 8 seconds of effective audio without silent segments.
             * >   - Format: 16kHz sampling rate, 16-bit depth, mono PCM audio file. The file name extension must be ".pcm".
             */
            sample_urls?: Record<string, string>;
        }

        export namespace Sal {
            /**
             * Selective attention lock mode:
             * - `locking`: Speaker Lock Mode. The agent locks onto the speaker, blocking 95% of ambient human voices and noise. You can enable this mode in two ways:
             *   - Seamless mode: When a user speaks loudly and clearly at the beginning of a conversation, the intelligent agent automatically recognizes the user as the speaker.
             *   - Personalized mode: When creating an agent, a speaker's voiceprint URL is pre-registered through the `sample_urls` field. The agent then locates the speaker based on the pre-registered voiceprint.
             * - `recognition`: Voiceprint recognition mode. The agent identifies different speakers and suppresses other background voices and environmental noise.
             */
            export const SalMode = {
                Locking: "locking",
                Recognition: "recognition",
            } as const;
            export type SalMode = (typeof SalMode)[keyof typeof SalMode];
        }

        /**
         * Agent configuration parameters.
         */
        export interface Parameters {
            /** Settings related to agent silence behavior. Does not apply when you integrate a `mllm`. */
            silence_config?: Parameters.SilenceConfig;
            /** Graceful hang-up settings for the agent. */
            farewell_config?: Parameters.FarewellConfig;
            /**
             * Agent data transmission channel:
             * - `rtm`: Use RTM transmission. This configuration takes effect only when `advanced_features.enable_rtm` is `true`.
             * - `datastream`: Use RTC data stream transport.
             */
            data_channel?: Parameters.DataChannel;
            /** Whether to receive agent performance data. This setting only takes effect when `advanced_features.enable_rtm` is `true`. */
            enable_metrics?: boolean;
            /** Whether to receive agent error events. This setting only takes effect when `advanced_features.enable_rtm` is `true`. */
            enable_error_message?: boolean;
        }

        export namespace Parameters {
            /**
             * Settings related to agent silence behavior. Does not apply when you integrate a `mllm`.
             */
            export interface SilenceConfig {
                /**
                 * Specifies the maximum duration (in milliseconds) that the agent can remain silent.
                 * - `0`: Disables the silent reminder feature.
                 * - `(0, 60000]`: Enables the silent reminder. You must also set `content`.
                 */
                timeout_ms?: number;
                /**
                 * Specifies how the agent behaves when the silent timeout is reached:
                 * - `speak`: Uses the TTS module to announce the silent prompt (`content`).
                 * - `think`: Appends the silent prompt (`content`) to the context and passes it to the LLM.
                 */
                action?: SilenceConfig.Action;
                /** Specifies the silent prompt message. The message use depends on the value of `action` parameter. */
                content?: string;
            }

            export namespace SilenceConfig {
                /**
                 * Specifies how the agent behaves when the silent timeout is reached:
                 * - `speak`: Uses the TTS module to announce the silent prompt (`content`).
                 * - `think`: Appends the silent prompt (`content`) to the context and passes it to the LLM.
                 */
                export const Action = {
                    Speak: "speak",
                    Think: "think",
                } as const;
                export type Action = (typeof Action)[keyof typeof Action];
            }

            /**
             * Graceful hang-up settings for the agent.
             */
            export interface FarewellConfig {
                /**
                 * Enable graceful leave:
                 * - `true`: When enabled, calling the POST method to stop the agent ensures that the agent is in an `IDLE` state before leaving the channel.
                 * - `false`: Disabled.
                 */
                graceful_enabled?: boolean;
                /** Graceful exit timeout (in seconds). Represents the maximum time to wait for the agent to enter an `IDLE` state before exiting the channel. This field is only effective when `graceful_enabled` is `true`. */
                graceful_timeout_seconds?: number;
            }

            /**
             * Agent data transmission channel:
             * - `rtm`: Use RTM transmission. This configuration takes effect only when `advanced_features.enable_rtm` is `true`.
             * - `datastream`: Use RTC data stream transport.
             */
            export const DataChannel = {
                Rtm: "rtm",
                Datastream: "datastream",
            } as const;
            export type DataChannel = (typeof DataChannel)[keyof typeof DataChannel];
        }
    }
}
