/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Agora from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace AgentManagement {
    export interface Options {
        environment?: core.Supplier<environments.AgoraEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        username: core.Supplier<string>;
        password: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

/**
 * Operations for managing conversational AI agents
 */
export class AgentManagement {
    protected readonly _options: AgentManagement.Options;

    constructor(_options: AgentManagement.Options) {
        this._options = _options;
    }

    /**
     * Create and start a Conversational AI agent instance.
     *
     * @param {string} appid - The App ID of the project.
     * @param {Agora.StartAgentRequest} request
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.startAgent("appid", {
     *         name: "unique_name",
     *         properties: {
     *             channel: "channel_name",
     *             token: "token",
     *             agent_rtc_uid: "1001",
     *             remote_rtc_uids: ["1002"],
     *             idle_timeout: 120,
     *             advanced_features: {
     *                 enable_aivad: true
     *             },
     *             asr: {
     *                 language: "en-US"
     *             },
     *             tts: {
     *                 vendor: "microsoft",
     *                 params: {
     *                     "key": "<your_tts_api_key>",
     *                     "region": "eastus",
     *                     "voice_name": "en-US-AndrewMultilingualNeural"
     *                 }
     *             },
     *             llm: {
     *                 url: "https://api.openai.com/v1/chat/completions",
     *                 api_key: "<your_llm_key>",
     *                 system_messages: [{
     *                         "role": "system",
     *                         "content": "You are a helpful chatbot."
     *                     }],
     *                 params: {
     *                     "model": "gpt-4o-mini"
     *                 },
     *                 max_history: 32,
     *                 greeting_message: "Hello, how can I assist you today?",
     *                 failure_message: "Please hold on a second."
     *             }
     *         }
     *     })
     */
    public startAgent(
        appid: string,
        request: Agora.StartAgentRequest,
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.StartAgentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__startAgent(appid, request, requestOptions));
    }

    private async __startAgent(
        appid: string,
        request: Agora.StartAgentRequest,
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.StartAgentResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/join`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.StartAgentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError("Timeout exceeded when calling POST /v2/projects/{appid}/join.");
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a list of agents that meet the specified conditions.
     *
     * @param {string} appid - The App ID of the project.
     * @param {Agora.ListAgentsRequest} request
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.listAgents("appid", {
     *         channel: "channel",
     *         from_time: 1.1,
     *         to_time: 1.1,
     *         state: "0",
     *         limit: 1,
     *         cursor: "cursor"
     *     })
     */
    public listAgents(
        appid: string,
        request: Agora.ListAgentsRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.ListAgentsResponse> {
        return core.HttpResponsePromise.fromPromise(this.__listAgents(appid, request, requestOptions));
    }

    private async __listAgents(
        appid: string,
        request: Agora.ListAgentsRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.ListAgentsResponse>> {
        const { channel, from_time: fromTime, to_time: toTime, state, limit, cursor } = request;
        const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
        if (channel != null) {
            _queryParams["channel"] = channel;
        }

        if (fromTime != null) {
            _queryParams["from_time"] = fromTime.toString();
        }

        if (toTime != null) {
            _queryParams["to_time"] = toTime.toString();
        }

        if (state != null) {
            _queryParams["state"] = state;
        }

        if (limit != null) {
            _queryParams["limit"] = limit.toString();
        }

        if (cursor != null) {
            _queryParams["cursor"] = cursor;
        }

        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.ListAgentsResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError("Timeout exceeded when calling GET /v2/projects/{appid}/agents.");
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get the current state information of the specified agent instance.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.queryAgentStatus("appid", "agentId")
     */
    public queryAgentStatus(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.QueryAgentStatusResponse> {
        return core.HttpResponsePromise.fromPromise(this.__queryAgentStatus(appid, agentId, requestOptions));
    }

    private async __queryAgentStatus(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.QueryAgentStatusResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.QueryAgentStatusResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling GET /v2/projects/{appid}/agents/{agentId}.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get the history of the conversation between the user and the agent.
     *
     * Call this endpoint while the agent is running to retrieve the conversation history. You can set the maximum number of cached entries using the `llm.max_history` parameter when calling the start agent endpoint. The default value is `32`.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.getAgentHistory("appid", "agentId")
     */
    public getAgentHistory(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.GetAgentHistoryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getAgentHistory(appid, agentId, requestOptions));
    }

    private async __getAgentHistory(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.GetAgentHistoryResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}/history`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.GetAgentHistoryResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling GET /v2/projects/{appid}/agents/{agentId}/history.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Stop the specified conversational agent instance.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.stopAgent("appid", "agentId")
     */
    public stopAgent(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__stopAgent(appid, agentId, requestOptions));
    }

    private async __stopAgent(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}/leave`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/leave.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Adjust Conversation AI Engine parameters at runtime.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {Agora.UpdateAgentRequest} request
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.updateAgent("appid", "agentId", {
     *         properties: {
     *             token: "007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
     *             llm: {
     *                 system_messages: [{
     *                         "role": "system",
     *                         "content": "You are a helpful assistant. xxx"
     *                     }, {
     *                         "role": "system",
     *                         "content": "Previously, user has talked about their favorite hobbies with some key topics: xxx"
     *                     }],
     *                 params: {
     *                     "model": "abab6.5s-chat",
     *                     "max_token": 1024
     *                 }
     *             }
     *         }
     *     })
     */
    public updateAgent(
        appid: string,
        agentId: string,
        request: Agora.UpdateAgentRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.UpdateAgentResponse> {
        return core.HttpResponsePromise.fromPromise(this.__updateAgent(appid, agentId, request, requestOptions));
    }

    private async __updateAgent(
        appid: string,
        agentId: string,
        request: Agora.UpdateAgentRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.UpdateAgentResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}/update`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.UpdateAgentResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/update.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Broadcast a custom message using the TTS module.
     *
     * During a conversation with an agent, call this endpoint to immediately broadcast a custom message using the TTS module. Upon receiving the request, the system interrupts the agent's speech and thought process to deliver the message. This broadcast can be interrupted by human voice.
     *
     * Note: The speak API is not supported when using `mllm` configuration.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {Agora.AgentSpeakRequest} request
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.agentSpeak("appid", "agentId", {
     *         text: "Sorry, the conversation content is not compliant.",
     *         priority: "INTERRUPT",
     *         interruptable: false
     *     })
     */
    public agentSpeak(
        appid: string,
        agentId: string,
        request: Agora.AgentSpeakRequest,
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.AgentSpeakResponse> {
        return core.HttpResponsePromise.fromPromise(this.__agentSpeak(appid, agentId, request, requestOptions));
    }

    private async __agentSpeak(
        appid: string,
        agentId: string,
        request: Agora.AgentSpeakRequest,
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.AgentSpeakResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}/speak`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.AgentSpeakResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/speak.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Interrupt the specified agent while speaking or thinking.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {Agora.AgentInterruptRequest} request
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.agentInterrupt("appid", "agentId")
     */
    public agentInterrupt(
        appid: string,
        agentId: string,
        request: Agora.AgentInterruptRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.AgentInterruptResponse> {
        return core.HttpResponsePromise.fromPromise(this.__agentInterrupt(appid, agentId, request, requestOptions));
    }

    private async __agentInterrupt(
        appid: string,
        agentId: string,
        request: Agora.AgentInterruptRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.AgentInterruptResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}/interrupt`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.AgentInterruptResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/interrupt.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        return core.BasicAuth.toAuthorizationHeader({
            username: await core.Supplier.get(this._options.username),
            password: await core.Supplier.get(this._options.password),
        });
    }
}
