/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Agora from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace AgentManagement {
    export interface Options {
        environment?: core.Supplier<environments.AgoraEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        username: core.Supplier<string>;
        password: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

/**
 * Operations for managing conversational AI agents
 */
export class AgentManagement {
    protected readonly _options: AgentManagement.Options;

    constructor(_options: AgentManagement.Options) {
        this._options = _options;
    }

    /**
     * Create and start a Conversational AI agent instance.
     *
     * @param {string} appid - The App ID of the project.
     * @param {Agora.AgentManagementStartRequest} request
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.start("appid", {
     *         name: "unique_name",
     *         properties: {
     *             channel: "channel_name",
     *             token: "token",
     *             agent_rtc_uid: "1001",
     *             remote_rtc_uids: ["1002"],
     *             idle_timeout: 120,
     *             advanced_features: {
     *                 enable_aivad: true
     *             },
     *             asr: {
     *                 language: "en-US"
     *             },
     *             tts: {
     *                 vendor: "microsoft",
     *                 params: {
     *                     "key": "<your_tts_api_key>",
     *                     "region": "eastus",
     *                     "voice_name": "en-US-AndrewMultilingualNeural"
     *                 }
     *             },
     *             llm: {
     *                 url: "https://api.openai.com/v1/chat/completions",
     *                 api_key: "<your_llm_key>",
     *                 system_messages: [{
     *                         "role": "system",
     *                         "content": "You are a helpful chatbot."
     *                     }],
     *                 params: {
     *                     "model": "gpt-4o-mini"
     *                 },
     *                 max_history: 32,
     *                 greeting_message: "Hello, how can I assist you today?",
     *                 failure_message: "Please hold on a second."
     *             }
     *         }
     *     })
     */
    public start(
        appid: string,
        request: Agora.AgentManagementStartRequest,
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.AgentManagementStartResponse> {
        return core.HttpResponsePromise.fromPromise(this.__start(appid, request, requestOptions));
    }

    private async __start(
        appid: string,
        request: Agora.AgentManagementStartRequest,
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.AgentManagementStartResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/join`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.AgentManagementStartResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError("Timeout exceeded when calling POST /v2/projects/{appid}/join.");
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve a list of agents that meet the specified conditions.
     *
     * @param {string} appid - The App ID of the project.
     * @param {Agora.AgentManagementListRequest} request
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.list("appid", {
     *         channel: "channel",
     *         from_time: 1.1,
     *         to_time: 1.1,
     *         state: "0",
     *         limit: 1,
     *         cursor: "cursor"
     *     })
     */
    public async list(
        appid: string,
        request: Agora.AgentManagementListRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.Page<Agora.AgentManagementListResponseDataListItem>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (
                request: Agora.AgentManagementListRequest,
            ): Promise<core.WithRawResponse<Agora.AgentManagementListResponse>> => {
                const { channel, from_time: fromTime, to_time: toTime, state, limit, cursor } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (channel != null) {
                    _queryParams["channel"] = channel;
                }
                if (fromTime != null) {
                    _queryParams["from_time"] = fromTime.toString();
                }
                if (toTime != null) {
                    _queryParams["to_time"] = toTime.toString();
                }
                if (state != null) {
                    _queryParams["state"] = state;
                }
                if (limit != null) {
                    _queryParams["limit"] = limit.toString();
                }
                if (cursor != null) {
                    _queryParams["cursor"] = cursor;
                }
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.AgoraEnvironment.Default,
                        `v2/projects/${encodeURIComponent(appid)}/agents`,
                    ),
                    method: "GET",
                    headers: mergeHeaders(
                        this._options?.headers,
                        mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                        requestOptions?.headers,
                    ),
                    queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return {
                        data: _response.body as Agora.AgentManagementListResponse,
                        rawResponse: _response.rawResponse,
                    };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.AgoraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.AgoraError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.AgoraTimeoutError(
                            "Timeout exceeded when calling GET /v2/projects/{appid}/agents.",
                        );
                    case "unknown":
                        throw new errors.AgoraError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Pageable<Agora.AgentManagementListResponse, Agora.AgentManagementListResponseDataListItem>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.meta?.cursor != null &&
                !(typeof response?.meta?.cursor === "string" && response?.meta?.cursor === ""),
            getItems: (response) => response?.data?.list ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.meta?.cursor));
            },
        });
    }

    /**
     * Get the current state information of the specified agent instance.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.get("appid", "agentId")
     */
    public get(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.AgentManagementGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(appid, agentId, requestOptions));
    }

    private async __get(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.AgentManagementGetResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.AgentManagementGetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling GET /v2/projects/{appid}/agents/{agentId}.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Get the history of the conversation between the user and the agent.
     *
     * Call this endpoint while the agent is running to retrieve the conversation history. You can set the maximum number of cached entries using the `llm.max_history` parameter when calling the start agent endpoint. The default value is `32`.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.getHistory("appid", "agentId")
     */
    public getHistory(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.AgentManagementGetHistoryResponse> {
        return core.HttpResponsePromise.fromPromise(this.__getHistory(appid, agentId, requestOptions));
    }

    private async __getHistory(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.AgentManagementGetHistoryResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}/history`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Agora.AgentManagementGetHistoryResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling GET /v2/projects/{appid}/agents/{agentId}/history.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Stop the specified conversational agent instance.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.stop("appid", "agentId")
     */
    public stop(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<void> {
        return core.HttpResponsePromise.fromPromise(this.__stop(appid, agentId, requestOptions));
    }

    private async __stop(
        appid: string,
        agentId: string,
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<void>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}/leave`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: undefined, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/leave.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Adjust Conversation AI Engine parameters at runtime.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {Agora.AgentManagementUpdateRequest} request
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.update("appid", "agentId", {
     *         properties: {
     *             token: "007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
     *             llm: {
     *                 system_messages: [{
     *                         "role": "system",
     *                         "content": "You are a helpful assistant. xxx"
     *                     }, {
     *                         "role": "system",
     *                         "content": "Previously, user has talked about their favorite hobbies with some key topics: xxx"
     *                     }],
     *                 params: {
     *                     "model": "abab6.5s-chat",
     *                     "max_token": 1024
     *                 }
     *             }
     *         }
     *     })
     */
    public update(
        appid: string,
        agentId: string,
        request: Agora.AgentManagementUpdateRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.AgentManagementUpdateResponse> {
        return core.HttpResponsePromise.fromPromise(this.__update(appid, agentId, request, requestOptions));
    }

    private async __update(
        appid: string,
        agentId: string,
        request: Agora.AgentManagementUpdateRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.AgentManagementUpdateResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}/update`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.AgentManagementUpdateResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/update.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Broadcast a custom message using the TTS module.
     *
     * During a conversation with an agent, call this endpoint to immediately broadcast a custom message using the TTS module. Upon receiving the request, the system interrupts the agent's speech and thought process to deliver the message. This broadcast can be interrupted by human voice.
     *
     * Note: The speak API is not supported when using `mllm` configuration.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {Agora.AgentManagementSpeakRequest} request
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.speak("appid", "agentId", {
     *         text: "Sorry, the conversation content is not compliant.",
     *         priority: "INTERRUPT",
     *         interruptable: false
     *     })
     */
    public speak(
        appid: string,
        agentId: string,
        request: Agora.AgentManagementSpeakRequest,
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.AgentManagementSpeakResponse> {
        return core.HttpResponsePromise.fromPromise(this.__speak(appid, agentId, request, requestOptions));
    }

    private async __speak(
        appid: string,
        agentId: string,
        request: Agora.AgentManagementSpeakRequest,
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.AgentManagementSpeakResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}/speak`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.AgentManagementSpeakResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/speak.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Interrupt the specified agent while speaking or thinking.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent instance ID you obtained after successfully calling `join` to start a conversational AI agent.
     * @param {Agora.AgentManagementInterruptRequest} request
     * @param {AgentManagement.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.agentManagement.interrupt("appid", "agentId")
     */
    public interrupt(
        appid: string,
        agentId: string,
        request: Agora.AgentManagementInterruptRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): core.HttpResponsePromise<Agora.AgentManagementInterruptResponse> {
        return core.HttpResponsePromise.fromPromise(this.__interrupt(appid, agentId, request, requestOptions));
    }

    private async __interrupt(
        appid: string,
        agentId: string,
        request: Agora.AgentManagementInterruptRequest = {},
        requestOptions?: AgentManagement.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.AgentManagementInterruptResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/agents/${encodeURIComponent(agentId)}/interrupt`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return {
                data: _response.body as Agora.AgentManagementInterruptResponse,
                rawResponse: _response.rawResponse,
            };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/agents/{agentId}/interrupt.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        return core.BasicAuth.toAuthorizationHeader({
            username: await core.Supplier.get(this._options.username),
            password: await core.Supplier.get(this._options.password),
        });
    }
}
