// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         appid: "appid",
 *         agent_id: "agent_id"
 *     }
 */
export interface HangupTelephonyRequest {
    /** The App ID of the project. */
    appid: string;
    /** The agent ID you obtained after successfully calling the API to initiate an outbound call. */
    agent_id: string;
}
