/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         name: "customer_service",
 *         sip: {
 *             to_number: "+19876543210",
 *             from_number: "+11234567890",
 *             sip_rtc_uid: "100",
 *             sip_rtc_token: "<agora_sip_rtc_token>"
 *         },
 *         pipeline_id: "fzufjlweixxxxnlp",
 *         properties: {
 *             channel: "<agora_channel>",
 *             token: "<agora_channel_token>",
 *             agent_rtc_uid: "111"
 *         }
 *     }
 *
 * @example
 *     {
 *         name: "customer_service",
 *         sip: {
 *             to_number: "+19876543210",
 *             from_number: "+11234567890",
 *             sip_rtc_uid: "100",
 *             sip_rtc_token: "<agora_sip_rtc_token>"
 *         },
 *         properties: {
 *             channel: "<agora_channel>",
 *             token: "<agora_channel_token>",
 *             agent_rtc_uid: "111"
 *         }
 *     }
 */
export interface InitiateOutboundCallRequest {
    /** The name identifier of the call session. */
    name: string;
    /** SIP (Session Initiation Protocol) call configuration object. */
    sip: InitiateOutboundCallRequest.Sip;
    /** The unique ID of a published project in AI Studio. */
    pipeline_id?: string;
    /**
     * Call attribute configuration. The content of this field varies depending on the invocation method:
     * - **Using pipeline ID**: Simply pass in `channel`, `token`, and `agent_rtc_uid`.
     * - **Using complete configuration**: Pass in the complete parameters of the [Start a conversational AI agent](https://docs.agora.io/en/conversational-ai/rest-api/agent/join) `properties`, including all required fields such as `channel`, `token`, `agent_rtc_uid`, `remote_rtc_uids`, `tts`, and `llm`.
     */
    properties: InitiateOutboundCallRequest.Properties;
}

export namespace InitiateOutboundCallRequest {
    /**
     * SIP (Session Initiation Protocol) call configuration object.
     */
    export interface Sip {
        /** Called number (target phone number), in E.164 format. */
        to_number: string;
        /** Caller ID (the number that initiated the call), in E.164 format. */
        from_number: string;
        /** The RTC UID used by the SIP gateway. */
        sip_rtc_uid: string;
        /** The RTC token used by the SIP gateway. */
        sip_rtc_token: string;
    }

    /**
     * Call attribute configuration. The content of this field varies depending on the invocation method:
     * - **Using pipeline ID**: Simply pass in `channel`, `token`, and `agent_rtc_uid`.
     * - **Using complete configuration**: Pass in the complete parameters of the [Start a conversational AI agent](https://docs.agora.io/en/conversational-ai/rest-api/agent/join) `properties`, including all required fields such as `channel`, `token`, `agent_rtc_uid`, `remote_rtc_uids`, `tts`, and `llm`.
     */
    export interface Properties {
        /** RTC channel name. */
        channel: string;
        /** RTC Channel Token. */
        token: string;
        /** The agent's user ID in the RTC channel. */
        agent_rtc_uid: string;
        /** Accepts any additional properties */
        [key: string]: any;
    }
}
