// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../../../../index.js";

/**
 * @example
 *     {
 *         appid: "appid"
 *     }
 */
export interface ListTelephonyRequest {
    /** The App ID of the project. */
    appid: string;
    /** Filter by phone number. Can be either the calling number or the called number. */
    number?: string;
    /** Query list start timestamp (in seconds). Default is 60 days ago. */
    from_time?: number;
    /** Query list end timestamp (in seconds). Default is current time. */
    to_time?: number;
    /**
     * Call type filter:
     * - `inbound`: Inbound call.
     * - `outbound`: Outbound call.
     *
     * If not specified, all call types are returned.
     */
    type?: Agora.ListTelephonyRequestType;
    /** Maximum number of items returned in a single page. */
    limit?: number;
    /** Pagination cursor. Use the `agent_id` from the previous page as the cursor for the next page. */
    cursor?: string;
}
