/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "../../../../environments.js";
import * as core from "../../../../core/index.js";
import * as Agora from "../../../index.js";
import { mergeHeaders, mergeOnlyDefinedHeaders } from "../../../../core/headers.js";
import * as errors from "../../../../errors/index.js";

export declare namespace Telephony {
    export interface Options {
        environment?: core.Supplier<environments.AgoraEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        username: core.Supplier<string>;
        password: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

/**
 * Operations for telephony and outbound calling
 */
export class Telephony {
    protected readonly _options: Telephony.Options;

    constructor(_options: Telephony.Options) {
        this._options = _options;
    }

    /**
     * Query historical call records for a specified appid based on the filter criteria.
     *
     * @param {string} appid - The App ID of the project.
     * @param {Agora.TelephonyListRequest} request
     * @param {Telephony.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.telephony.list("appid", {
     *         number: "number",
     *         from_time: 1,
     *         to_time: 1,
     *         type: "inbound",
     *         limit: 1,
     *         cursor: "cursor"
     *     })
     */
    public async list(
        appid: string,
        request: Agora.TelephonyListRequest = {},
        requestOptions?: Telephony.RequestOptions,
    ): Promise<core.Page<Agora.TelephonyListResponseDataListItem>> {
        const list = core.HttpResponsePromise.interceptFunction(
            async (request: Agora.TelephonyListRequest): Promise<core.WithRawResponse<Agora.TelephonyListResponse>> => {
                const { number: number_, from_time: fromTime, to_time: toTime, type: type_, limit, cursor } = request;
                const _queryParams: Record<string, string | string[] | object | object[] | null> = {};
                if (number_ != null) {
                    _queryParams["number"] = number_;
                }
                if (fromTime != null) {
                    _queryParams["from_time"] = fromTime.toString();
                }
                if (toTime != null) {
                    _queryParams["to_time"] = toTime.toString();
                }
                if (type_ != null) {
                    _queryParams["type"] = type_;
                }
                if (limit != null) {
                    _queryParams["limit"] = limit.toString();
                }
                if (cursor != null) {
                    _queryParams["cursor"] = cursor;
                }
                const _response = await core.fetcher({
                    url: core.url.join(
                        (await core.Supplier.get(this._options.baseUrl)) ??
                            (await core.Supplier.get(this._options.environment)) ??
                            environments.AgoraEnvironment.Default,
                        `v2/projects/${encodeURIComponent(appid)}/call`,
                    ),
                    method: "GET",
                    headers: mergeHeaders(
                        this._options?.headers,
                        mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                        requestOptions?.headers,
                    ),
                    queryParameters: { ..._queryParams, ...requestOptions?.queryParams },
                    timeoutMs:
                        requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
                    maxRetries: requestOptions?.maxRetries,
                    abortSignal: requestOptions?.abortSignal,
                });
                if (_response.ok) {
                    return { data: _response.body as Agora.TelephonyListResponse, rawResponse: _response.rawResponse };
                }
                if (_response.error.reason === "status-code") {
                    throw new errors.AgoraError({
                        statusCode: _response.error.statusCode,
                        body: _response.error.body,
                        rawResponse: _response.rawResponse,
                    });
                }
                switch (_response.error.reason) {
                    case "non-json":
                        throw new errors.AgoraError({
                            statusCode: _response.error.statusCode,
                            body: _response.error.rawBody,
                            rawResponse: _response.rawResponse,
                        });
                    case "timeout":
                        throw new errors.AgoraTimeoutError(
                            "Timeout exceeded when calling GET /v2/projects/{appid}/call.",
                        );
                    case "unknown":
                        throw new errors.AgoraError({
                            message: _response.error.errorMessage,
                            rawResponse: _response.rawResponse,
                        });
                }
            },
        );
        const dataWithRawResponse = await list(request).withRawResponse();
        return new core.Pageable<Agora.TelephonyListResponse, Agora.TelephonyListResponseDataListItem>({
            response: dataWithRawResponse.data,
            rawResponse: dataWithRawResponse.rawResponse,
            hasNextPage: (response) =>
                response?.meta?.cursor != null &&
                !(typeof response?.meta?.cursor === "string" && response?.meta?.cursor === ""),
            getItems: (response) => response?.data?.list ?? [],
            loadPage: (response) => {
                return list(core.setObjectProperty(request, "cursor", response?.meta?.cursor));
            },
        });
    }

    /**
     * Initiate an outbound call to a specified number and create an agent to join the specified RTC channel.
     *
     * Use this endpoint to initiate an outbound call to the specified number and create an agent that joins the target RTC channel. The agent waits for the callee to answer.
     *
     * @param {string} appid - The App ID of the project.
     * @param {Agora.TelephonyCallRequest} request
     * @param {Telephony.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.telephony.call("appid", {
     *         name: "customer_service",
     *         sip: {
     *             to_number: "+19876543210",
     *             from_number: "+11234567890",
     *             sip_rtc_uid: "100",
     *             sip_rtc_token: "<agora_sip_rtc_token>"
     *         },
     *         pipeline_id: "fzufjlweixxxxnlp",
     *         properties: {
     *             channel: "<agora_channel>",
     *             token: "<agora_channel_token>",
     *             agent_rtc_uid: "111"
     *         }
     *     })
     *
     * @example
     *     await client.telephony.call("appid", {
     *         name: "customer_service",
     *         sip: {
     *             to_number: "+19876543210",
     *             from_number: "+11234567890",
     *             sip_rtc_uid: "100",
     *             sip_rtc_token: "<agora_sip_rtc_token>"
     *         },
     *         properties: {
     *             channel: "<agora_channel>",
     *             token: "<agora_channel_token>",
     *             agent_rtc_uid: "111"
     *         }
     *     })
     */
    public call(
        appid: string,
        request: Agora.TelephonyCallRequest,
        requestOptions?: Telephony.RequestOptions,
    ): core.HttpResponsePromise<Agora.TelephonyCallResponse> {
        return core.HttpResponsePromise.fromPromise(this.__call(appid, request, requestOptions));
    }

    private async __call(
        appid: string,
        request: Agora.TelephonyCallRequest,
        requestOptions?: Telephony.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.TelephonyCallResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/call`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.TelephonyCallResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError("Timeout exceeded when calling POST /v2/projects/{appid}/call.");
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Retrieve the call status and related information of a specified agent.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent ID you obtained after successfully calling the API to initiate an outbound call.
     * @param {Telephony.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.telephony.get("appid", "agent_id")
     */
    public get(
        appid: string,
        agentId: string,
        requestOptions?: Telephony.RequestOptions,
    ): core.HttpResponsePromise<Agora.TelephonyGetResponse> {
        return core.HttpResponsePromise.fromPromise(this.__get(appid, agentId, requestOptions));
    }

    private async __get(
        appid: string,
        agentId: string,
        requestOptions?: Telephony.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.TelephonyGetResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/calls/${encodeURIComponent(agentId)}`,
            ),
            method: "GET",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            queryParameters: requestOptions?.queryParams,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.TelephonyGetResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling GET /v2/projects/{appid}/calls/{agent_id}.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    /**
     * Instruct the agent to proactively hang up the ongoing call and leave the RTC channel.
     *
     * @param {string} appid - The App ID of the project.
     * @param {string} agentId - The agent ID you obtained after successfully calling the API to initiate an outbound call.
     * @param {Agora.TelephonyHangupRequest} request
     * @param {Telephony.RequestOptions} requestOptions - Request-specific configuration.
     *
     * @example
     *     await client.telephony.hangup("appid", "agent_id")
     */
    public hangup(
        appid: string,
        agentId: string,
        request: Agora.TelephonyHangupRequest = {},
        requestOptions?: Telephony.RequestOptions,
    ): core.HttpResponsePromise<Agora.TelephonyHangupResponse> {
        return core.HttpResponsePromise.fromPromise(this.__hangup(appid, agentId, request, requestOptions));
    }

    private async __hangup(
        appid: string,
        agentId: string,
        request: Agora.TelephonyHangupRequest = {},
        requestOptions?: Telephony.RequestOptions,
    ): Promise<core.WithRawResponse<Agora.TelephonyHangupResponse>> {
        const _response = await core.fetcher({
            url: core.url.join(
                (await core.Supplier.get(this._options.baseUrl)) ??
                    (await core.Supplier.get(this._options.environment)) ??
                    environments.AgoraEnvironment.Default,
                `v2/projects/${encodeURIComponent(appid)}/calls/${encodeURIComponent(agentId)}/hangup`,
            ),
            method: "POST",
            headers: mergeHeaders(
                this._options?.headers,
                mergeOnlyDefinedHeaders({ Authorization: await this._getAuthorizationHeader() }),
                requestOptions?.headers,
            ),
            contentType: "application/json",
            queryParameters: requestOptions?.queryParams,
            requestType: "json",
            body: request,
            timeoutMs: requestOptions?.timeoutInSeconds != null ? requestOptions.timeoutInSeconds * 1000 : 60000,
            maxRetries: requestOptions?.maxRetries,
            abortSignal: requestOptions?.abortSignal,
        });
        if (_response.ok) {
            return { data: _response.body as Agora.TelephonyHangupResponse, rawResponse: _response.rawResponse };
        }

        if (_response.error.reason === "status-code") {
            throw new errors.AgoraError({
                statusCode: _response.error.statusCode,
                body: _response.error.body,
                rawResponse: _response.rawResponse,
            });
        }

        switch (_response.error.reason) {
            case "non-json":
                throw new errors.AgoraError({
                    statusCode: _response.error.statusCode,
                    body: _response.error.rawBody,
                    rawResponse: _response.rawResponse,
                });
            case "timeout":
                throw new errors.AgoraTimeoutError(
                    "Timeout exceeded when calling POST /v2/projects/{appid}/calls/{agent_id}/hangup.",
                );
            case "unknown":
                throw new errors.AgoraError({
                    message: _response.error.errorMessage,
                    rawResponse: _response.rawResponse,
                });
        }
    }

    protected async _getAuthorizationHeader(): Promise<string | undefined> {
        return core.BasicAuth.toAuthorizationHeader({
            username: await core.Supplier.get(this._options.username),
            password: await core.Supplier.get(this._options.password),
        });
    }
}
