// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Amazon Polly Text-to-Speech configuration (Beta).
 */
export interface AmazonTts {
    params: Agora.AmazonTtsParams;
    /** Controls whether the TTS module skips bracketed content when reading LLM response text. */
    skip_patterns?: number[];
}
