// This file was auto-generated by Fern from our API Definition.

/**
 * Amazon Polly TTS configuration parameters.
 */
export interface AmazonTtsParams {
    /** AWS access key */
    access_key: string;
    /** AWS secret key */
    secret_key: string;
    /** AWS region (e.g., "us-east-1") */
    region: string;
    /** Amazon Polly voice ID */
    voice_id: string;
}
