// This file was auto-generated by Fern from our API Definition.

/**
 * Cartesia TTS configuration parameters.
 */
export interface CartesiaTtsParams {
    /** Cartesia API key */
    key: string;
    /** Cartesia voice ID */
    voice_id: string;
    /** Model ID (optional) */
    model_id?: string;
}
