// This file was auto-generated by Fern from our API Definition.

/**
 * ElevenLabs TTS configuration parameters.
 */
export interface ElevenLabsTtsParams {
    /** WebSocket URL (e.g., "wss://api.elevenlabs.io/v1") */
    base_url?: string;
    /** ElevenLabs API key */
    key: string;
    /** Model ID (e.g., "eleven_flash_v2_5") */
    model_id: string;
    /** Voice ID (e.g., "pNInz6obpgDQGcFmaJgB") */
    voice_id: string;
    /** Audio sample rate in Hz (16kHz for Akool, 24kHz for HeyGen) */
    sample_rate?: number;
}
