// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * ElevenLabs Text-to-Speech configuration.
 */
export interface ElevenLabsTts {
    params: Agora.ElevenLabsTtsParams;
    /** Controls whether the TTS module skips bracketed content when reading LLM response text. */
    skip_patterns?: number[];
}
