// This file was auto-generated by Fern from our API Definition.

/**
 * Agora Fengming ASR configuration parameters.
 */
export interface FengmingAsrParams {
    /** A list of hotwords to improve ASR accuracy. */
    keywords?: string[];
    /** Accepts any additional properties */
    [key: string]: any;
}
