// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Agora Fengming ASR configuration.
 */
export interface FengmingAsr {
    language?: Agora.AsrLanguage;
    /** A list of hotwords to improve ASR accuracy. */
    keywords?: string[];
    params?: Agora.FengmingAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
