// This file was auto-generated by Fern from our API Definition.

/**
 * Fish Audio TTS configuration parameters.
 */
export interface FishAudioTtsParams {
    /** Fish Audio API key */
    key: string;
    /** Fish Audio reference ID */
    reference_id: string;
}
