// This file was auto-generated by Fern from our API Definition.

/**
 * Google Gemini ASR configuration parameters.
 */
export interface GeminiAsrParams {
    /** Google Gemini API key. */
    api_key: string;
    /** Gemini transcription model identifier. */
    model: string;
    /** Audio sample rate in Hz. */
    sample_rate?: number;
    /** Language code for speech recognition. */
    language?: string;
    /** Whether to include word-level timestamps in transcription results. */
    word_timestamp?: boolean;
    /** Accepts any additional properties */
    [key: string]: any;
}
