// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Google Gemini ASR configuration.
 */
export interface GeminiAsr {
    language?: Agora.AsrLanguage;
    params: Agora.GeminiAsrParams;
    /** Accepts any additional properties */
    [key: string]: any;
}
