// This file was auto-generated by Fern from our API Definition.

/**
 * Google Gemini ASR configuration parameters.
 */
export interface GeminiAsrParams {
    /** The Google Gemini API key used to authenticate requests. */
    api_key: string;
    /** The Gemini transcription model identifier. */
    model: string;
    /** The audio sample rate in Hz. */
    sample_rate?: number | null;
    /** The language code for speech recognition. This takes precedence over the top-level `asr.language` value. */
    language?: string;
    /** Whether to include word-level timestamps in the transcription results. */
    word_timestamp?: boolean;
    /** Accepts any additional properties */
    [key: string]: any;
}
