// This file was auto-generated by Fern from our API Definition.

/**
 * Google TTS configuration parameters.
 */
export interface GoogleTtsParams {
    /** Google Cloud API key */
    key: string;
    /** Google voice name */
    voice_name: string;
    /** Language code (e.g., "en-US") */
    language_code?: string;
    /** Sample rate in Hz (default depends on selected voice) */
    sample_rate_hertz?: number;
}
