// This file was auto-generated by Fern from our API Definition.

/**
 * Groq TTS configuration parameters.
 */
export interface GroqTtsParams {
    /** Groq API key */
    key: string;
    /** Model name */
    model?: string;
}
