// This file was auto-generated by Fern from our API Definition.

/**
 * Hume AI TTS configuration parameters.
 */
export interface HumeAiTtsParams {
    /** Hume AI API key */
    key: string;
    /** Hume AI configuration ID */
    config_id?: string;
}
