// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Inline REST tool definition. `type: function` combined with `server` declares a REST tool.
 * Phase 1a executes the HTTP request synchronously and returns the raw result to the model context.
 */
export interface LlmTool {
    /** Tool type. Must be `function`. */
    type: "function";
    function: Agora.LlmToolFunction;
    execution?: Agora.LlmToolExecution;
    server: Agora.LlmToolServer;
    /** Accepts any additional properties */
    [key: string]: any;
}
