// This file was auto-generated by Fern from our API Definition.

/**
 * Microsoft Azure TTS configuration parameters.
 */
export interface MicrosoftTtsParams {
    /** Microsoft Azure API key */
    key: string;
    /** Azure region (e.g., "eastus") */
    region: string;
    /** Voice name (e.g., "en-US-AndrewMultilingualNeural") */
    voice_name: string;
}
