// This file was auto-generated by Fern from our API Definition.

/**
 * MiniMax TTS configuration parameters.
 */
export interface MiniMaxTtsParams {
    /** MiniMax API key */
    key: string;
    /** Voice ID */
    voice_id?: string;
    /** Model name */
    model?: string;
}
