// This file was auto-generated by Fern from our API Definition.

/**
 * Murf TTS configuration parameters.
 */
export interface MurfTtsParams {
    /** Murf API key */
    key: string;
    /** Voice ID (e.g., Ariana, Natalie, Ken) */
    voice_id: string;
    /** Voice style (e.g., Angry, Sad, Conversational, Newscast) */
    style?: string;
}
