// This file was auto-generated by Fern from our API Definition.

/**
 * Rime TTS configuration parameters.
 */
export interface RimeTtsParams {
    /** Rime API key */
    key: string;
    /** Rime speaker ID */
    speaker: string;
    /** Model ID (optional) */
    model_id?: string;
}
