// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Rime Text-to-Speech configuration (Beta).
 */
export interface RimeTts {
    params: Agora.RimeTtsParams;
    /** Controls whether the TTS module skips bracketed content when reading LLM response text. */
    skip_patterns?: number[];
}
