// This file was auto-generated by Fern from our API Definition.

/**
 * Sarvam TTS configuration parameters.
 */
export interface SarvamTtsParams {
    /** Sarvam API subscription key */
    key: string;
    /** Voice ID (e.g., anushka, abhilash, karun, hitesh, manisha, vidya, arya) */
    speaker: string;
    /** Target language code (e.g., en-IN) */
    target_language_code: string;
}
