// This file was auto-generated by Fern from our API Definition.

/**
 * Sarvam TTS configuration parameters (Beta).
 */
export interface SarvamTtsParams {
    /** Sarvam API key */
    api_key: string;
    /** Voice ID */
    voice_id?: string;
    /** Model name */
    model?: string;
}
