// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

export type Tts =
    | Agora.Tts.Microsoft
    | Agora.Tts.Elevenlabs
    | Agora.Tts.Minimax
    | Agora.Tts.Cartesia
    | Agora.Tts.Openai
    | Agora.Tts.Humeai
    | Agora.Tts.Rime
    | Agora.Tts.Fishaudio
    | Agora.Tts.Groq
    | Agora.Tts.Google
    | Agora.Tts.Amazon
    | Agora.Tts.Sarvam;

export namespace Tts {
    export interface Microsoft extends Agora.MicrosoftTts {
        vendor: "microsoft";
    }

    export interface Elevenlabs extends Agora.ElevenLabsTts {
        vendor: "elevenlabs";
    }

    export interface Minimax extends Agora.MiniMaxTts {
        vendor: "minimax";
    }

    export interface Cartesia extends Agora.CartesiaTts {
        vendor: "cartesia";
    }

    export interface Openai extends Agora.OpenAiTts {
        vendor: "openai";
    }

    export interface Humeai extends Agora.HumeAiTts {
        vendor: "humeai";
    }

    export interface Rime extends Agora.RimeTts {
        vendor: "rime";
    }

    export interface Fishaudio extends Agora.FishAudioTts {
        vendor: "fishaudio";
    }

    export interface Groq extends Agora.GroqTts {
        vendor: "groq";
    }

    export interface Google extends Agora.GoogleTts {
        vendor: "google";
    }

    export interface Amazon extends Agora.AmazonTts {
        vendor: "amazon";
    }

    export interface Sarvam extends Agora.SarvamTts {
        vendor: "sarvam";
    }
}
