// This file was auto-generated by Fern from our API Definition.

import type * as Agora from "../index.js";

/**
 * Typecast Text-to-Speech configuration.
 */
export interface TypecastTts {
    params: Agora.TypecastTtsParams;
    /** Controls whether the TTS module skips bracketed content when reading LLM response text. */
    skip_patterns?: number[];
}
