// This file was auto-generated by Fern from our API Definition.

/**
 * Typecast TTS configuration parameters.
 */
export interface TypecastTtsParams {
    /** Typecast API key. */
    api_key: string;
    /** Typecast voice identifier (for example, "tc_60e5426de8b95f1d3000d7b5"). */
    voice_id: string;
    /** Typecast TTS model name (for example, "ssfm-v30"). */
    model: string;
    /** Accepts any additional properties */
    [key: string]: any;
}
