// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         provider: "byo",
 *         phone_number: "+19876543210",
 *         label: "Sales Hotline",
 *         inbound: true,
 *         outbound: true,
 *         inbound_config: {
 *             allowed_addresses: ["112.126.15.64/27"]
 *         },
 *         outbound_config: {
 *             address: "xxx:xxx@sip.example.com",
 *             transport: "tls"
 *         }
 *     }
 *
 * @example
 *     {
 *         provider: "byo",
 *         phone_number: "+19876543210",
 *         label: "Sales Hotline",
 *         inbound: true,
 *         outbound: true,
 *         inbound_config: {
 *             allowed_addresses: ["112.126.15.64/27"]
 *         },
 *         outbound_config: {
 *             address: "xxx:xxx@sip.example.com",
 *             transport: "tls"
 *         }
 *     }
 */
export interface AddPhoneNumberManagementRequest {
    /**
     * Number provider:
     * - `byo`: BYO (Bring Your Own)
     * - `twilio`: Twilio
     */
    provider: AddPhoneNumberManagementRequest.Provider;
    /** Telephone number in E.164 format. */
    phone_number: string;
    /** A label used to identify the number. */
    label: string;
    /** Whether the number supports inbound calls. */
    inbound?: boolean;
    /** Whether the number supports outbound calls. */
    outbound?: boolean;
    /** SIP inbound call configuration. */
    inbound_config: AddPhoneNumberManagementRequest.InboundConfig;
    /** SIP outbound call configuration. */
    outbound_config: AddPhoneNumberManagementRequest.OutboundConfig;
}

export namespace AddPhoneNumberManagementRequest {
    /**
     * Number provider:
     * - `byo`: BYO (Bring Your Own)
     * - `twilio`: Twilio
     */
    export const Provider = {
        Byo: "byo",
        Twilio: "twilio",
    } as const;
    export type Provider = (typeof Provider)[keyof typeof Provider];

    /**
     * SIP inbound call configuration.
     */
    export interface InboundConfig {
        /** List of allowed IP addresses. For example `112.126.15.64/27` */
        allowed_addresses?: string[];
    }

    /**
     * SIP outbound call configuration.
     */
    export interface OutboundConfig {
        /** SIP address. For example `xxx:xxx@sip.example.com` */
        address?: string;
        /** Transport protocol. For example `tls` */
        transport?: string;
        /** Number prefix. For example `6036` */
        prefix?: string;
    }
}
