// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phone_number: "phone_number"
 *     }
 */
export interface DeletePhoneNumberManagementRequest {
    /** Telephone number in E.164 format. For example, +11234567890. */
    phone_number: string;
}
