/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         inbound_config: {
 *             pipeline_id: "xxxxx"
 *         },
 *         outbound_config: {
 *             pipeline_id: "xxxxx"
 *         }
 *     }
 */
export interface PhoneNumberManagementUpdateRequest {
    /** Update inbound call configuration. Passing `null` will clear the configuration. */
    inbound_config?: PhoneNumberManagementUpdateRequest.InboundConfig;
    /** Update outbound call configuration. Passing `null` will clear the configuration. */
    outbound_config?: PhoneNumberManagementUpdateRequest.OutboundConfig;
}

export namespace PhoneNumberManagementUpdateRequest {
    /**
     * Update inbound call configuration. Passing `null` will clear the configuration.
     */
    export interface InboundConfig {
        /** Pipeline ID. */
        pipeline_id?: string;
    }

    /**
     * Update outbound call configuration. Passing `null` will clear the configuration.
     */
    export interface OutboundConfig {
        /** Pipeline ID. */
        pipeline_id?: string;
    }
}
