// This file was auto-generated by Fern from our API Definition.

/**
 * @example
 *     {
 *         phone_number: "phone_number",
 *         inbound_config: {
 *             pipeline_id: "xxxxx"
 *         },
 *         outbound_config: {
 *             pipeline_id: "xxxxx"
 *         }
 *     }
 */
export interface UpdatePhoneNumberManagementRequest {
    /** Telephone number in E.164 format. For example, +11234567890. */
    phone_number: string;
    /** Update inbound call configuration. Passing `null` will clear the configuration. */
    inbound_config?: UpdatePhoneNumberManagementRequest.InboundConfig | null;
    /** Update outbound call configuration. Passing `null` will clear the configuration. */
    outbound_config?: UpdatePhoneNumberManagementRequest.OutboundConfig | null;
}

export namespace UpdatePhoneNumberManagementRequest {
    /**
     * Update inbound call configuration. Passing `null` will clear the configuration.
     */
    export interface InboundConfig {
        /** Pipeline ID. */
        pipeline_id?: string;
    }

    /**
     * Update outbound call configuration. Passing `null` will clear the configuration.
     */
    export interface OutboundConfig {
        /** Pipeline ID. */
        pipeline_id?: string;
    }
}
