/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         text: "Sorry, the conversation content is not compliant.",
 *         priority: "INTERRUPT",
 *         interruptable: false
 *     }
 */
export interface AgentSpeakRequest {
    /** The broadcast message text. The maximum length of the text content is 512 bytes. */
    text: string;
    /**
     * Sets the priority of the message broadcast:
     * - `INTERRUPT`: High priority. The agent immediately interrupts the current interaction to announce the message.
     * - `APPEND`: Medium priority. The agent announces the message after the current interaction ends.
     * - `IGNORE`: Low priority. If the agent is busy interacting, it ignores and discards the broadcast; the message is only announced if the agent is not interacting.
     */
    priority?: AgentSpeakRequest.Priority;
    /**
     * Whether to allow users to interrupt the agent's broadcast by speaking:
     * - `true`: Allow
     * - `false`: Don't allow
     */
    interruptable?: boolean;
}

export namespace AgentSpeakRequest {
    /**
     * Sets the priority of the message broadcast:
     * - `INTERRUPT`: High priority. The agent immediately interrupts the current interaction to announce the message.
     * - `APPEND`: Medium priority. The agent announces the message after the current interaction ends.
     * - `IGNORE`: Low priority. If the agent is busy interacting, it ignores and discards the broadcast; the message is only announced if the agent is not interacting.
     */
    export type Priority = "INTERRUPT" | "APPEND" | "IGNORE";
    export const Priority = {
        Interrupt: "INTERRUPT",
        Append: "APPEND",
        Ignore: "IGNORE",
    } as const;
}
