/**
 * This file was auto-generated by Fern from our API Definition.
 */

/**
 * @example
 *     {
 *         properties: {
 *             token: "007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
 *             llm: {
 *                 system_messages: [{
 *                         "role": "system",
 *                         "content": "You are a helpful assistant. xxx"
 *                     }, {
 *                         "role": "system",
 *                         "content": "Previously, user has talked about their favorite hobbies with some key topics: xxx"
 *                     }],
 *                 params: {
 *                     "model": "abab6.5s-chat",
 *                     "max_token": 1024
 *                 }
 *             }
 *         }
 *     }
 */
export interface AgentManagementUpdateRequest {
    /** Configuration properties to update. */
    properties?: AgentManagementUpdateRequest.Properties;
}

export namespace AgentManagementUpdateRequest {
    /**
     * Configuration properties to update.
     */
    export interface Properties {
        /** The authentication token used by the agent to join the channel. */
        token?: string;
        /** Large Language Model (LLM) settings. */
        llm?: Properties.Llm;
        /** Multimodal Large Language Model (MLLM) configuration for real-time audio and text processing. */
        mllm?: Properties.Mllm;
    }

    export namespace Properties {
        /**
         * Large Language Model (LLM) settings.
         */
        export interface Llm {
            /** A set of predefined messages appended to the beginning of each LLM request. These messages help control the LLM's output and can include role definitions, prompts, response examples, and more. This field must be compatible with the OpenAI protocol. */
            system_messages?: Record<string, unknown>[];
            /** Additional LLM information included in the message body, such as the model used, the maximum number of tokens, and more. Supported configurations vary by LLM provider. Refer to the provider's documentation for details. Updating this field overwrites the configuration set when the agent was created. When updating, make sure to pass the complete `params` field. */
            params?: Record<string, unknown>;
        }

        /**
         * Multimodal Large Language Model (MLLM) configuration for real-time audio and text processing.
         */
        export interface Mllm {
            /** Additional MLLM configuration parameters. See [MLLM Overview](https://docs.agora.io/en/conversational-ai/models/mllm/overview) for details. */
            params?: Record<string, unknown>;
        }
    }
}
