/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AgentManagementGetHistoryResponse {
    /** Unique identifier of the agent. */
    agent_id?: string;
    /** Agent creation timestamp. */
    start_ts?: number;
    /** Agent status. Only supports querying the running agent. */
    status?: "RUNNING";
    /** Agent history. */
    contents?: AgentManagementGetHistoryResponse.Contents.Item[];
}

export namespace AgentManagementGetHistoryResponse {
    export type Contents = Contents.Item[];

    export namespace Contents {
        export interface Item {
            /**
             * The message sender:
             * - `user`: User
             * - `assistant`: AI agent
             */
            role?: Item.Role;
            /** Message content. */
            content?: string;
        }

        export namespace Item {
            /**
             * The message sender:
             * - `user`: User
             * - `assistant`: AI agent
             */
            export type Role = "user" | "assistant";
            export const Role = {
                User: "user",
                Assistant: "assistant",
            } as const;
        }
    }
}
