/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface AgentManagementListResponse {
    /** Agent data. */
    data?: AgentManagementListResponse.Data;
    /** Returns meta information about the list. */
    meta?: AgentManagementListResponse.Meta;
    /** Request status. */
    status?: string;
}

export namespace AgentManagementListResponse {
    /**
     * Agent data.
     */
    export interface Data {
        /** The number of agents returned. */
        count?: number;
        /** A list of agents that meets the criteria. */
        list?: Data.List.Item[];
    }

    export namespace Data {
        export type List = List.Item[];

        export namespace List {
            export interface Item {
                /** Agent creation timestamp. */
                start_ts?: number;
                /** The current state of the agent. */
                status?: Item.Status;
                /** The agent ID. */
                agent_id?: string;
            }

            export namespace Item {
                /**
                 * The current state of the agent.
                 */
                export type Status = "IDLE" | "STARTING" | "RUNNING" | "STOPPING" | "STOPPED" | "RECOVERING" | "FAILED";
                export const Status = {
                    Idle: "IDLE",
                    Starting: "STARTING",
                    Running: "RUNNING",
                    Stopping: "STOPPING",
                    Stopped: "STOPPED",
                    Recovering: "RECOVERING",
                    Failed: "FAILED",
                } as const;
            }
        }
    }

    /**
     * Returns meta information about the list.
     */
    export interface Meta {
        /** Paging cursor. */
        cursor?: string;
        /** The total number of agents that meet the query conditions. */
        total?: number;
    }
}
