// This file was auto-generated by Fern from our API Definition.

export const ListAgentManagementRequestState = {
    Zero: "0",
    One: "1",
    Two: "2",
    Three: "3",
    Four: "4",
    Five: "5",
    Six: "6",
} as const;
export type ListAgentManagementRequestState =
    (typeof ListAgentManagementRequestState)[keyof typeof ListAgentManagementRequestState];
