/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface QueryAgentStatusResponse {
    /** Request message. */
    message?: string;
    /** Agent creation timestamp. */
    start_ts?: number;
    /** Agent stop timestamp. */
    stop_ts?: number;
    /**
     * Current status:
     * - `IDLE` (0): Agent is idle.
     * - `STARTING` (1): The agent is being started.
     * - `RUNNING` (2): The agent is running.
     * - `STOPPING` (3): The agent is stopping.
     * - `STOPPED` (4): The agent has exited.
     * - `RECOVERING` (5): The agent is recovering.
     * - `FAILED` (6): The agent failed to execute.
     */
    status?: QueryAgentStatusResponse.Status;
    /** Unique id of the agent instance */
    agent_id?: string;
}

export namespace QueryAgentStatusResponse {
    /**
     * Current status:
     * - `IDLE` (0): Agent is idle.
     * - `STARTING` (1): The agent is being started.
     * - `RUNNING` (2): The agent is running.
     * - `STOPPING` (3): The agent is stopping.
     * - `STOPPED` (4): The agent has exited.
     * - `RECOVERING` (5): The agent is recovering.
     * - `FAILED` (6): The agent failed to execute.
     */
    export type Status = "IDLE" | "STARTING" | "RUNNING" | "STOPPING" | "STOPPED" | "RECOVERING" | "FAILED";
    export const Status = {
        Idle: "IDLE",
        Starting: "STARTING",
        Running: "RUNNING",
        Stopping: "STOPPING",
        Stopped: "STOPPED",
        Recovering: "RECOVERING",
        Failed: "FAILED",
    } as const;
}
