/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { AgoraClient } from "../../src/Client";

describe("AgentManagement", () => {
    test("start", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "unique_name",
            properties: {
                channel: "channel_name",
                token: "token",
                agent_rtc_uid: "1001",
                remote_rtc_uids: ["1002"],
                idle_timeout: 120,
                advanced_features: { enable_aivad: true },
                asr: { language: "en-US" },
                tts: {
                    vendor: "microsoft",
                    params: {
                        key: "<your_tts_api_key>",
                        region: "eastus",
                        voice_name: "en-US-AndrewMultilingualNeural",
                    },
                },
                llm: {
                    url: "https://api.openai.com/v1/chat/completions",
                    api_key: "<your_llm_key>",
                    system_messages: [{ role: "system", content: "You are a helpful chatbot." }],
                    params: { model: "gpt-4o-mini" },
                    max_history: 32,
                    greeting_message: "Hello, how can I assist you today?",
                    failure_message: "Please hold on a second.",
                },
            },
        };
        const rawResponseBody = { agent_id: "1NT29X10YHxxxxxWJOXLYHNYB", create_ts: 1737111452, status: "RUNNING" };
        server
            .mockEndpoint()
            .post("/v2/projects/appid/join")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentManagement.start("appid", {
            name: "unique_name",
            properties: {
                channel: "channel_name",
                token: "token",
                agent_rtc_uid: "1001",
                remote_rtc_uids: ["1002"],
                idle_timeout: 120,
                advanced_features: {
                    enable_aivad: true,
                },
                asr: {
                    language: "en-US",
                },
                tts: {
                    vendor: "microsoft",
                    params: {
                        key: "<your_tts_api_key>",
                        region: "eastus",
                        voice_name: "en-US-AndrewMultilingualNeural",
                    },
                },
                llm: {
                    url: "https://api.openai.com/v1/chat/completions",
                    api_key: "<your_llm_key>",
                    system_messages: [
                        {
                            role: "system",
                            content: "You are a helpful chatbot.",
                        },
                    ],
                    params: {
                        model: "gpt-4o-mini",
                    },
                    max_history: 32,
                    greeting_message: "Hello, how can I assist you today?",
                    failure_message: "Please hold on a second.",
                },
            },
        });
        expect(response).toEqual({
            agent_id: "1NT29X10YHxxxxxWJOXLYHNYB",
            create_ts: 1737111452,
            status: "RUNNING",
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });

        const rawResponseBody = {
            message: "agent exits with reason: xxxx",
            start_ts: 1735035893,
            stop_ts: 1735035900,
            status: "FAILED",
            agent_id: "1NT29X11GQSxxxxxNU80BEIN56XF",
        };
        server
            .mockEndpoint()
            .get("/v2/projects/appid/agents/agentId")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentManagement.get("appid", "agentId");
        expect(response).toEqual({
            message: "agent exits with reason: xxxx",
            start_ts: 1735035893,
            stop_ts: 1735035900,
            status: "FAILED",
            agent_id: "1NT29X11GQSxxxxxNU80BEIN56XF",
        });
    });

    test("getHistory", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });

        const rawResponseBody = {
            agent_id: "xxxx",
            start_ts: 123,
            status: "RUNNING",
            contents: [
                { role: "user", content: "hello." },
                { role: "assistant", content: "hi, how can I help you?" },
            ],
        };
        server
            .mockEndpoint()
            .get("/v2/projects/appid/agents/agentId/history")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentManagement.getHistory("appid", "agentId");
        expect(response).toEqual({
            agent_id: "xxxx",
            start_ts: 123,
            status: "RUNNING",
            contents: [
                {
                    role: "user",
                    content: "hello.",
                },
                {
                    role: "assistant",
                    content: "hi, how can I help you?",
                },
            ],
        });
    });

    test("stop", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });

        server.mockEndpoint().post("/v2/projects/appid/agents/agentId/leave").respondWith().statusCode(200).build();

        const response = await client.agentManagement.stop("appid", "agentId");
        expect(response).toEqual(undefined);
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });
        const rawRequestBody = {
            properties: {
                token: "007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
                llm: {
                    system_messages: [
                        { role: "system", content: "You are a helpful assistant. xxx" },
                        {
                            role: "system",
                            content:
                                "Previously, user has talked about their favorite hobbies with some key topics: xxx",
                        },
                    ],
                    params: { model: "abab6.5s-chat", max_token: 1024 },
                },
            },
        };
        const rawResponseBody = { agent_id: "1NT29X10YHxxxxxWJOXLYHNYB", create_ts: 1737123456, status: "RUNNING" };
        server
            .mockEndpoint()
            .post("/v2/projects/appid/agents/agentId/update")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentManagement.update("appid", "agentId", {
            properties: {
                token: "007eJxTYxxxxxxxxxxIaHMLAAAA0ex66",
                llm: {
                    system_messages: [
                        {
                            role: "system",
                            content: "You are a helpful assistant. xxx",
                        },
                        {
                            role: "system",
                            content:
                                "Previously, user has talked about their favorite hobbies with some key topics: xxx",
                        },
                    ],
                    params: {
                        model: "abab6.5s-chat",
                        max_token: 1024,
                    },
                },
            },
        });
        expect(response).toEqual({
            agent_id: "1NT29X10YHxxxxxWJOXLYHNYB",
            create_ts: 1737123456,
            status: "RUNNING",
        });
    });

    test("speak", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });
        const rawRequestBody = {
            text: "Sorry, the conversation content is not compliant.",
            priority: "INTERRUPT",
            interruptable: false,
        };
        const rawResponseBody = { agent_id: "1NT29XxxxxxxxxELWEHC8OS", channel: "test_channel", start_ts: 1744877089 };
        server
            .mockEndpoint()
            .post("/v2/projects/appid/agents/agentId/speak")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentManagement.speak("appid", "agentId", {
            text: "Sorry, the conversation content is not compliant.",
            priority: "INTERRUPT",
            interruptable: false,
        });
        expect(response).toEqual({
            agent_id: "1NT29XxxxxxxxxELWEHC8OS",
            channel: "test_channel",
            start_ts: 1744877089,
        });
    });

    test("interrupt", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = { agent_id: "1NT29XxxxxxxxxELWEHC8OS", channel: "test_channel", start_ts: 1744877089 };
        server
            .mockEndpoint()
            .post("/v2/projects/appid/agents/agentId/interrupt")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.agentManagement.interrupt("appid", "agentId");
        expect(response).toEqual({
            agent_id: "1NT29XxxxxxxxxELWEHC8OS",
            channel: "test_channel",
            start_ts: 1744877089,
        });
    });
});
