/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { AgoraClient } from "../../src/Client";

describe("PhoneNumberManagement", () => {
    test("list", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });

        const rawResponseBody = [
            {
                provider: "twilio",
                phone_number: "+11234567890",
                label: "Customer Support Line",
                inbound: true,
                outbound: true,
                associated_pipeline: { pipeline_id: "pipeline_0987654321fedcba", pipeline_name: "Customer Service" },
                inbound_config: { key: "value" },
                outbound_config: { key: "value" },
            },
            {
                provider: "byo",
                phone_number: "+19876543210",
                label: "Sales",
                inbound: false,
                outbound: true,
                associated_pipeline: { pipeline_id: "pipeline_id", pipeline_name: "pipeline_name" },
                inbound_config: { key: "value" },
                outbound_config: { key: "value" },
            },
        ];
        server.mockEndpoint().get("/v2/phone-numbers").respondWith().statusCode(200).jsonBody(rawResponseBody).build();

        const response = await client.phoneNumberManagement.list();
        expect(response).toEqual([
            {
                provider: "twilio",
                phone_number: "+11234567890",
                label: "Customer Support Line",
                inbound: true,
                outbound: true,
                associated_pipeline: {
                    pipeline_id: "pipeline_0987654321fedcba",
                    pipeline_name: "Customer Service",
                },
                inbound_config: {
                    key: "value",
                },
                outbound_config: {
                    key: "value",
                },
            },
            {
                provider: "byo",
                phone_number: "+19876543210",
                label: "Sales",
                inbound: false,
                outbound: true,
                associated_pipeline: {
                    pipeline_id: "pipeline_id",
                    pipeline_name: "pipeline_name",
                },
                inbound_config: {
                    key: "value",
                },
                outbound_config: {
                    key: "value",
                },
            },
        ]);
    });

    test("add", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });
        const rawRequestBody = {
            provider: "byo",
            phone_number: "+19876543210",
            label: "Sales Hotline",
            inbound: true,
            outbound: true,
            inbound_config: { allowed_addresses: ["112.126.15.64/27"] },
            outbound_config: { address: "xxx:xxx@sip.example.com", transport: "tls" },
        };
        const rawResponseBody = {
            phone_number: "+11234567890",
            label: "Customer Support Line",
            provider: "byo",
            inbound: true,
            outbound: true,
            associated_pipeline: { pipeline_id: "pipeline_id", pipeline_name: "pipeline_name" },
        };
        server
            .mockEndpoint()
            .post("/v2/phone-numbers")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumberManagement.add({
            provider: "byo",
            phone_number: "+19876543210",
            label: "Sales Hotline",
            inbound: true,
            outbound: true,
            inbound_config: {
                allowed_addresses: ["112.126.15.64/27"],
            },
            outbound_config: {
                address: "xxx:xxx@sip.example.com",
                transport: "tls",
            },
        });
        expect(response).toEqual({
            phone_number: "+11234567890",
            label: "Customer Support Line",
            provider: "byo",
            inbound: true,
            outbound: true,
            associated_pipeline: {
                pipeline_id: "pipeline_id",
                pipeline_name: "pipeline_name",
            },
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });

        const rawResponseBody = {
            provider: "byo",
            phone_number: "+11234567890",
            label: "Customer Support Line",
            inbound: true,
            outbound: true,
            associated_pipeline: { pipeline_id: "pipeline_id", pipeline_name: "pipeline_name" },
            inbound_config: { key: "value" },
            outbound_config: { key: "value" },
        };
        server
            .mockEndpoint()
            .get("/v2/phone-numbers/phone_number")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumberManagement.get("phone_number");
        expect(response).toEqual({
            provider: "byo",
            phone_number: "+11234567890",
            label: "Customer Support Line",
            inbound: true,
            outbound: true,
            associated_pipeline: {
                pipeline_id: "pipeline_id",
                pipeline_name: "pipeline_name",
            },
            inbound_config: {
                key: "value",
            },
            outbound_config: {
                key: "value",
            },
        });
    });

    test("delete", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });

        server.mockEndpoint().delete("/v2/phone-numbers/phone_number").respondWith().statusCode(200).build();

        const response = await client.phoneNumberManagement.delete("phone_number");
        expect(response).toEqual(undefined);
    });

    test("update", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });
        const rawRequestBody = { inbound_config: { pipeline_id: "xxxxx" }, outbound_config: { pipeline_id: "xxxxx" } };
        const rawResponseBody = {
            provider: "byo",
            phone_number: "+11234567890",
            label: "Customer Support Line",
            inbound: true,
            outbound: true,
            associated_pipeline: { pipeline_id: "pipeline_id_12345", pipeline_name: "New Support Bot" },
            inbound_config: { key: "value" },
            outbound_config: { key: "value" },
        };
        server
            .mockEndpoint()
            .patch("/v2/phone-numbers/phone_number")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.phoneNumberManagement.update("phone_number", {
            inbound_config: {
                pipeline_id: "xxxxx",
            },
            outbound_config: {
                pipeline_id: "xxxxx",
            },
        });
        expect(response).toEqual({
            provider: "byo",
            phone_number: "+11234567890",
            label: "Customer Support Line",
            inbound: true,
            outbound: true,
            associated_pipeline: {
                pipeline_id: "pipeline_id_12345",
                pipeline_name: "New Support Bot",
            },
            inbound_config: {
                key: "value",
            },
            outbound_config: {
                key: "value",
            },
        });
    });
});
