/**
 * This file was auto-generated by Fern from our API Definition.
 */

import { mockServerPool } from "../mock-server/MockServerPool";
import { AgoraClient } from "../../src/Client";

describe("Telephony", () => {
    test("call", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });
        const rawRequestBody = {
            name: "customer_service",
            sip: {
                to_number: "+19876543210",
                from_number: "+11234567890",
                sip_rtc_uid: "100",
                sip_rtc_token: "<agora_sip_rtc_token>",
            },
            pipeline_id: "fzufjlweixxxxnlp",
            properties: { channel: "<agora_channel>", token: "<agora_channel_token>", agent_rtc_uid: "111" },
        };
        const rawResponseBody = { agent_id: "A42AK62PExxxxxxxx74LN47MF46E" };
        server
            .mockEndpoint()
            .post("/v2/projects/appid/call")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.telephony.call("appid", {
            name: "customer_service",
            sip: {
                to_number: "+19876543210",
                from_number: "+11234567890",
                sip_rtc_uid: "100",
                sip_rtc_token: "<agora_sip_rtc_token>",
            },
            pipeline_id: "fzufjlweixxxxnlp",
            properties: {
                channel: "<agora_channel>",
                token: "<agora_channel_token>",
                agent_rtc_uid: "111",
            },
        });
        expect(response).toEqual({
            agent_id: "A42AK62PExxxxxxxx74LN47MF46E",
        });
    });

    test("get", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });

        const rawResponseBody = {
            to_number: "1300000000",
            from_number: "1330000000",
            pipeline_id: "28",
            type: "inbound",
            agent_id: "A42AA22AT45xxxxxxRH76AM92W",
            channel: "channel_1111",
            reason: "request",
            create_ts: 1758498988,
            state: "hangup",
            stop_ts: 1758498995,
        };
        server
            .mockEndpoint()
            .get("/v2/projects/appid/calls/agent_id")
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.telephony.get("appid", "agent_id");
        expect(response).toEqual({
            to_number: "1300000000",
            from_number: "1330000000",
            pipeline_id: "28",
            type: "inbound",
            agent_id: "A42AA22AT45xxxxxxRH76AM92W",
            channel: "channel_1111",
            reason: "request",
            create_ts: 1758498988,
            state: "hangup",
            stop_ts: 1758498995,
        });
    });

    test("hangup", async () => {
        const server = mockServerPool.createServer();
        const client = new AgoraClient({ username: "test", password: "test", environment: server.baseUrl });
        const rawRequestBody = {};
        const rawResponseBody = {};
        server
            .mockEndpoint()
            .post("/v2/projects/appid/calls/agent_id/hangup")
            .jsonBody(rawRequestBody)
            .respondWith()
            .statusCode(200)
            .jsonBody(rawResponseBody)
            .build();

        const response = await client.telephony.hangup("appid", "agent_id");
        expect(response).toEqual({});
    });
});
