// This file was auto-generated by Fern from our API Definition.

export interface GetTelephonyResponse {
    /** The number called. */
    to_number?: string;
    /** Caller ID. */
    from_number?: string;
    /** The unique ID of a published project in AI Studio. Can be obtained in AI Studio - Project - Release Management. */
    pipeline_id?: string;
    /**
     * Call type:
     * - `inbound`: Inbound call.
     * - `outbound`: Outbound call.
     */
    type?: GetTelephonyResponse.Type;
    /** A unique identifier for the call session. */
    agent_id?: string;
    /** RTC channel name. */
    channel?: string;
    /**
     * Reason for call ending:
     * - `request`: Actively hung up.
     * - `hangup`: The other party hung up.
     * - `failed`: Call failed.
     */
    reason?: GetTelephonyResponse.Reason;
    /** Call creation timestamp (in seconds). */
    create_ts?: number;
    /**
     * Call status:
     * - `answered`: The call was answered.
     * - `hangup`: The call was disconnected.
     */
    state?: GetTelephonyResponse.State;
    /** Call end timestamp (in seconds). Returns `0` or `null` if the call has not ended. */
    stop_ts?: number | null;
}

export namespace GetTelephonyResponse {
    /**
     * Call type:
     * - `inbound`: Inbound call.
     * - `outbound`: Outbound call.
     */
    export const Type = {
        Inbound: "inbound",
        Outbound: "outbound",
    } as const;
    export type Type = (typeof Type)[keyof typeof Type];
    /**
     * Reason for call ending:
     * - `request`: Actively hung up.
     * - `hangup`: The other party hung up.
     * - `failed`: Call failed.
     */
    export const Reason = {
        Request: "request",
        Hangup: "hangup",
        Failed: "failed",
    } as const;
    export type Reason = (typeof Reason)[keyof typeof Reason];
    /**
     * Call status:
     * - `answered`: The call was answered.
     * - `hangup`: The call was disconnected.
     */
    export const State = {
        Answered: "answered",
        Hangup: "hangup",
    } as const;
    export type State = (typeof State)[keyof typeof State];
}
