// This file was auto-generated by Fern from our API Definition.

export interface ListTelephonyResponse {
    /** Call data object. */
    data?: ListTelephonyResponse.Data;
    /** Metadata about the list. */
    meta?: ListTelephonyResponse.Meta;
    /** Request status. */
    status?: string;
}

export namespace ListTelephonyResponse {
    /**
     * Call data object.
     */
    export interface Data {
        /** The number of calls returned in this response. */
        count?: number;
        /** A list of calls that meet the criteria. */
        list?: Data.List.Item[];
    }

    export namespace Data {
        export type List = List.Item[];

        export namespace List {
            export interface Item {
                /** The number called. */
                to_number?: string;
                /** Caller ID. */
                from_number?: string;
                /** The unique ID of a published project in AI Studio. Can be obtained in AI Studio - Project - Release Management. */
                pipeline_id?: string;
                /**
                 * Call type:
                 * - `inbound`: Inbound call.
                 * - `outbound`: Outbound call.
                 */
                type?: Item.Type;
                /** A unique identifier for the call session. */
                agent_id?: string;
                /** RTC channel name. */
                channel?: string;
                /** Call creation timestamp (in seconds). */
                create_ts?: number;
                /**
                 * Call status:
                 * - `answered`: The call was answered.
                 * - `hangup`: The call was disconnected.
                 */
                state?: Item.State;
                /** Call end timestamp (in seconds). Returns `0` or `null` if the call has not ended. */
                stop_ts?: number | null;
            }

            export namespace Item {
                /**
                 * Call type:
                 * - `inbound`: Inbound call.
                 * - `outbound`: Outbound call.
                 */
                export const Type = {
                    Inbound: "inbound",
                    Outbound: "outbound",
                } as const;
                export type Type = (typeof Type)[keyof typeof Type];
                /**
                 * Call status:
                 * - `answered`: The call was answered.
                 * - `hangup`: The call was disconnected.
                 */
                export const State = {
                    Answered: "answered",
                    Hangup: "hangup",
                } as const;
                export type State = (typeof State)[keyof typeof State];
            }
        }
    }

    /**
     * Metadata about the list.
     */
    export interface Meta {
        /** Pagination cursor for the next page. */
        cursor?: string;
        /** The total number of calls that meet the query criteria. */
        total?: number;
    }
}
