// This file was auto-generated by Fern from our API Definition.

export const ListTelephonyRequestType = {
    Inbound: "inbound",
    Outbound: "outbound",
} as const;
export type ListTelephonyRequestType = (typeof ListTelephonyRequestType)[keyof typeof ListTelephonyRequestType];
