/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type RetrieveCallRecordsRequestType = "inbound" | "outbound";
export const RetrieveCallRecordsRequestType = {
    Inbound: "inbound",
    Outbound: "outbound",
} as const;
