/**
 * This file was auto-generated by Fern from our API Definition.
 */

export type TelephonyListRequestType = "inbound" | "outbound";
export const TelephonyListRequestType = {
    Inbound: "inbound",
    Outbound: "outbound",
} as const;
