/**
 * This file was auto-generated by Fern from our API Definition.
 */

export interface TelephonyCallResponse {
    /** Unique ID of the agent instance. Use it to query call status, control call flow, and perform other operations. */
    agent_id?: string;
}
