// This file was auto-generated by Fern from our API Definition.

import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { AgoraClient as BaseAgoraClient } from "./Client.js";
import { Area, Pool } from "./core/domain/index.js";

export declare namespace AgoraClient {
    export interface Options extends Omit<BaseClientOptions, "baseUrl" | "environment" | "username" | "password"> {
        /** The area to use for regional URL selection */
        area: Area;
        /** Agora App ID — used as the `appid` path parameter and for RTC token generation */
        appId: string;
        /** Agora App Certificate — used to sign RTC tokens. Keep this secret. */
        appCertificate: string;
        /** Customer ID from Agora Console (REST API authentication) */
        customerId: string;
        /** Customer Secret from Agora Console (REST API authentication) */
        customerSecret: string;
    }

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * AgoraClient extends the base client with domain pool support for
 * regional URL cycling and automatic domain selection.
 *
 * This client automatically:
 * - Selects the best domain based on DNS resolution
 * - Cycles through region prefixes on request failures
 * - Supports US, EU, AP, and CN areas
 * - Generates RTC tokens when starting agents (no manual token management)
 *
 * @example
 * ```typescript
 * import { AgoraClient, Area } from "agora-sdk";
 *
 * const client = new AgoraClient({
 *     area: Area.US,
 *     appId: "your-app-id",
 *     appCertificate: "your-app-certificate",
 *     customerId: "your-customer-id",
 *     customerSecret: "your-customer-secret",
 * });
 * ```
 */
export class AgoraClient extends BaseAgoraClient {
    protected readonly _pool: Pool;
    /** Agora App ID */
    public readonly appId: string;
    /** Agora App Certificate (used for RTC token signing) */
    public readonly appCertificate: string;

    constructor(options: AgoraClient.Options) {
        const pool = new Pool(options.area);
        const { customerId, customerSecret, ...rest } = options;
        super({
            ...rest,
            username: customerId,
            password: customerSecret,
            baseUrl: () => pool.getCurrentURL(),
        });
        this._pool = pool;
        this.appId = options.appId;
        this.appCertificate = options.appCertificate;
    }

    /**
     * Get the underlying domain pool for advanced usage.
     * You can use this to manually cycle regions or select the best domain.
     */
    public get pool(): Pool {
        return this._pool;
    }

    /**
     * Cycle to the next region prefix in the pool.
     * Call this when a request fails to try a different region.
     */
    public nextRegion(): void {
        this._pool.nextRegion();
    }

    /**
     * Select the best domain using DNS resolution.
     * This is automatically called periodically, but you can call it manually.
     */
    public async selectBestDomain(signal?: AbortSignal): Promise<void> {
        await this._pool.selectBestDomain(signal);
    }

    /**
     * Get the current URL being used for requests.
     */
    public getCurrentURL(): string {
        return this._pool.getCurrentURL();
    }
}
