// This file was auto-generated by Fern from our API Definition.

import { AgentsClient } from "./api/resources/agents/client/Client.js";
import { PhoneNumbersClient } from "./api/resources/phoneNumbers/client/Client.js";
import { TelephonyClient } from "./api/resources/telephony/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { type NormalizedClientOptionsWithAuth, normalizeClientOptionsWithAuth } from "./BaseClient.js";
import { Area, Pool } from "./core/domain/index.js";

export declare namespace AgoraPoolClient {
    export interface Options extends Omit<BaseClientOptions, "baseUrl" | "environment"> {
        /** The area to use for regional URL selection */
        area: Area;
    }

    export interface RequestOptions extends BaseRequestOptions {}
}

/**
 * AgoraPoolClient is a wrapper around AgoraClient that uses a domain pool
 * for regional URL cycling and automatic domain selection.
 *
 * This client automatically:
 * - Selects the best domain based on DNS resolution
 * - Cycles through region prefixes on request failures
 * - Supports US, EU, AP, and CN areas
 *
 * @example
 * ```typescript
 * import { AgoraPoolClient, Area } from "agora-sdk";
 *
 * const client = new AgoraPoolClient({
 *     area: Area.US,
 *     username: "your-username",
 *     password: "your-password",
 * });
 * ```
 */
export class AgoraPoolClient {
    protected readonly _options: NormalizedClientOptionsWithAuth<BaseClientOptions>;
    protected readonly _pool: Pool;
    protected _agents: AgentsClient | undefined;
    protected _telephony: TelephonyClient | undefined;
    protected _phoneNumbers: PhoneNumbersClient | undefined;

    constructor(options: AgoraPoolClient.Options) {
        this._pool = new Pool(options.area);

        const baseClientOptions: BaseClientOptions = {
            ...options,
            baseUrl: () => this._pool.getCurrentURL(),
        };

        this._options = normalizeClientOptionsWithAuth(baseClientOptions);
    }

    /**
     * Get the underlying domain pool for advanced usage.
     * You can use this to manually cycle regions or select the best domain.
     */
    public get pool(): Pool {
        return this._pool;
    }

    /**
     * Cycle to the next region prefix in the pool.
     * Call this when a request fails to try a different region.
     */
    public nextRegion(): void {
        this._pool.nextRegion();
    }

    /**
     * Select the best domain using DNS resolution.
     * This is automatically called periodically, but you can call it manually.
     */
    public async selectBestDomain(signal?: AbortSignal): Promise<void> {
        await this._pool.selectBestDomain(signal);
    }

    /**
     * Get the current URL being used for requests.
     */
    public getCurrentURL(): string {
        return this._pool.getCurrentURL();
    }

    public get agents(): AgentsClient {
        return (this._agents ??= new AgentsClient(this._options));
    }

    public get telephony(): TelephonyClient {
        return (this._telephony ??= new TelephonyClient(this._options));
    }

    public get phoneNumbers(): PhoneNumbersClient {
        return (this._phoneNumbers ??= new PhoneNumbersClient(this._options));
    }
}
