/**
 * This file was auto-generated by Fern from our API Definition.
 */

import * as environments from "./environments.js";
import * as core from "./core/index.js";
import { mergeHeaders } from "./core/headers.js";
import { AgentManagement } from "./api/resources/agentManagement/client/Client.js";
import { Telephony } from "./api/resources/telephony/client/Client.js";
import { PhoneNumberManagement } from "./api/resources/phoneNumberManagement/client/Client.js";

export declare namespace AgoraClient {
    export interface Options {
        environment?: core.Supplier<environments.AgoraEnvironment | string>;
        /** Specify a custom URL to connect the client to. */
        baseUrl?: core.Supplier<string>;
        username: core.Supplier<string>;
        password: core.Supplier<string>;
        /** Additional headers to include in requests. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }

    export interface RequestOptions {
        /** The maximum time to wait for a response in seconds. */
        timeoutInSeconds?: number;
        /** The number of times to retry the request. Defaults to 2. */
        maxRetries?: number;
        /** A hook to abort the request. */
        abortSignal?: AbortSignal;
        /** Additional query string parameters to include in the request. */
        queryParams?: Record<string, unknown>;
        /** Additional headers to include in the request. */
        headers?: Record<string, string | core.Supplier<string | undefined> | undefined>;
    }
}

export class AgoraClient {
    protected readonly _options: AgoraClient.Options;
    protected _agentManagement: AgentManagement | undefined;
    protected _telephony: Telephony | undefined;
    protected _phoneNumberManagement: PhoneNumberManagement | undefined;

    constructor(_options: AgoraClient.Options) {
        this._options = {
            ..._options,
            headers: mergeHeaders(
                {
                    "X-Fern-Language": "JavaScript",
                    "X-Fern-SDK-Name": "agora-sdk",
                    "X-Fern-SDK-Version": "0.0.3",
                    "User-Agent": "agora-sdk/AUTO",
                    "X-Fern-Runtime": core.RUNTIME.type,
                    "X-Fern-Runtime-Version": core.RUNTIME.version,
                },
                _options?.headers,
            ),
        };
    }

    public get agentManagement(): AgentManagement {
        return (this._agentManagement ??= new AgentManagement(this._options));
    }

    public get telephony(): Telephony {
        return (this._telephony ??= new Telephony(this._options));
    }

    public get phoneNumberManagement(): PhoneNumberManagement {
        return (this._phoneNumberManagement ??= new PhoneNumberManagement(this._options));
    }
}
