// This file was auto-generated by Fern from our API Definition.

import { AgentManagementClient } from "./api/resources/agentManagement/client/Client.js";
import { PhoneNumberManagementClient } from "./api/resources/phoneNumberManagement/client/Client.js";
import { TelephonyClient } from "./api/resources/telephony/client/Client.js";
import type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
import { normalizeClientOptions } from "./BaseClient.js";

export declare namespace AgoraClient {
    export interface Options extends BaseClientOptions {}

    export interface RequestOptions extends BaseRequestOptions {}
}

export class AgoraClient {
    protected readonly _options: AgoraClient.Options;
    protected _agentManagement: AgentManagementClient | undefined;
    protected _telephony: TelephonyClient | undefined;
    protected _phoneNumberManagement: PhoneNumberManagementClient | undefined;

    constructor(options: AgoraClient.Options) {
        this._options = normalizeClientOptions(options);
    }

    public get agentManagement(): AgentManagementClient {
        return (this._agentManagement ??= new AgentManagementClient(this._options));
    }

    public get telephony(): TelephonyClient {
        return (this._telephony ??= new TelephonyClient(this._options));
    }

    public get phoneNumberManagement(): PhoneNumberManagementClient {
        return (this._phoneNumberManagement ??= new PhoneNumberManagementClient(this._options));
    }
}
