// This file was auto-generated by Fern from our API Definition.

export const AgoraEnvironment = {
    Default: "https://api.agora.io/api/conversational-ai-agent",
} as const;

export type AgoraEnvironment = typeof AgoraEnvironment.Default;
