export * as Agora from "./api/index.js";
export { AgoraClient } from "./AgoraPoolClient.js";
export type { BaseClientOptions, BaseRequestOptions } from "./BaseClient.js";
export { AgoraEnvironment } from "./environments.js";
export { AgoraError, AgoraTimeoutError } from "./errors/index.js";
export { Area } from "./core/domain/index.js";
export * from "./exports.js";

// Wrapper layer exports - clean, ergonomic API
export {
    Agent,
    AgentSession,
    generateRtcToken,
    isHeyGenAvatar,
    isAkoolAvatar,
    validateAvatarConfig,
    validateTtsSampleRate,
    toBaseAvatarConfig,
    // Base vendor classes
    BaseLLM,
    BaseTTS,
    BaseSTT,
    BaseMLLM,
    BaseAvatar,
    // LLM vendors
    OpenAI,
    AzureOpenAI,
    Anthropic,
    Gemini,
    // TTS vendors
    ElevenLabsTTS,
    MicrosoftTTS,
    OpenAITTS,
    CartesiaTTS,
    GoogleTTS,
    AmazonTTS,
    HumeAITTS,
    RimeTTS,
    FishAudioTTS,
    GroqTTS,
    // STT vendors
    SpeechmaticsSTT,
    DeepgramSTT,
    MicrosoftSTT,
    OpenAISTT,
    GoogleSTT,
    AmazonSTT,
    AssemblyAISTT,
    AresSTT,
    // MLLM vendors
    OpenAIRealtime,
    VertexAI,
    // Avatar vendors
    HeyGenAvatar,
    AkoolAvatar,
} from "./wrapper/index.js";
export type {
    AgentOptions,
    AgentSessionOptions,
    GenerateTokenOptions,
    AgentSessionEvent,
    AgentSessionEventHandler,
    // Sample rate types
    SampleRate,
    ElevenLabsSampleRate,
    MicrosoftSampleRate,
    CartesiaSampleRate,
    HeyGenSampleRate,
    AkoolSampleRate,
    // Clean type aliases
    LlmConfig,
    LlmStyle,
    SttConfig,
    SttVendor,
    TtsConfig,
    MllmConfig,
    MllmVendor,
    MllmStyle,
    AvatarConfig,
    AvatarVendor,
    TurnDetectionConfig,
    TurnDetectionType,
    InterruptMode,
    Eagerness,
    SalConfig,
    SalMode,
    AdvancedFeatures,
    SessionParams,
    SilenceConfig,
    SilenceAction,
    FarewellConfig,
    AgentConfig,
    AgentConfigUpdate,
    SessionOptions,
    SessionStatus,
    SessionInfo,
    SessionListResponse,
    SessionSummary,
    ConversationHistory,
    ConversationTurn,
    ConversationRole,
    SayOptions,
    SpeakPriority,
    // Vendor option types
    OpenAIOptions,
    AzureOpenAIOptions,
    AnthropicOptions,
    GeminiOptions,
    ElevenLabsTTSOptions,
    MicrosoftTTSOptions,
    OpenAITTSOptions,
    CartesiaTTSOptions,
    GoogleTTSOptions,
    AmazonTTSOptions,
    HumeAITTSOptions,
    RimeTTSOptions,
    FishAudioTTSOptions,
    GroqTTSOptions,
    SpeechmaticsSTTOptions,
    DeepgramSTTOptions,
    MicrosoftSTTOptions,
    OpenAISTTOptions,
    GoogleSTTOptions,
    AmazonSTTOptions,
    AssemblyAISTTOptions,
    AresSTTOptions,
    OpenAIRealtimeOptions,
    VertexAIOptions,
    HeyGenAvatarOptions,
    AkoolAvatarOptions,
} from "./wrapper/index.js";
