// This file was auto-generated by Fern from our API Definition.

export interface AddPhoneNumbersResponse {
    /** A telephone number in E.164 format, used as a unique identifier. */
    phone_number?: string;
    /** A label used to identify the number. */
    label?: string;
    /** Number provider. */
    provider?: string;
    /** Whether the number supports inbound calls. */
    inbound?: boolean;
    /** Whether the number supports outbound calls. */
    outbound?: boolean;
    /** The associated pipeline information. Returns `null` if no pipeline is associated. */
    associated_pipeline?: AddPhoneNumbersResponse.AssociatedPipeline | null;
}

export namespace AddPhoneNumbersResponse {
    /**
     * The associated pipeline information. Returns `null` if no pipeline is associated.
     */
    export interface AssociatedPipeline {
        /** Pipeline ID. */
        pipeline_id?: string;
        /** Pipeline name. */
        pipeline_name?: string;
    }
}
